//! SFU Session Manager
//!
//! Bridges the API signaling layer with the SFU forwarding plane by managing
//! server-side `PeerConnection` instances. When a room's WebRTC participant
//! count reaches the configured `sfu_threshold`, new peers get a server-side
//! `PeerConnection` instead of pure P2P signaling relay.
//!
//! ## Lifecycle
//!
//! 1. A peer sends a WebRTC Join message
//! 2. The messaging layer checks `should_use_sfu()` against the current RTC peer count
//! 3. If SFU mode is warranted, `create_session()` creates a `PeerConnection` and
//!    registers the peer with the `SfuManager`
//! 4. Subsequent Offer/Answer/ICE messages are routed to the server-side
//!    `PeerConnection` instead of being relayed peer-to-peer
//! 5. When the peer sends WebRTC Leave, `remove_session()` cleans up

use crate::manager::SfuManager;
use crate::peer::SfuPeer;
use crate::room::SfuRoom;
use crate::rtcp_handler::RtcpHandler;
use crate::track::{MediaTrack, TrackKind};
use crate::types::{PeerId, RoomId, TrackId};
use crate::webrtc_control::{IceManager, PeerConnection};
use anyhow::{anyhow, Result};
use dashmap::DashMap;
use std::net::IpAddr;
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::mpsc;
use tokio::task::JoinHandle;
use tokio_util::sync::CancellationToken;
use tracing::{debug, error, info, warn};
use webrtc::ice_transport::ice_candidate::RTCIceCandidate;
use webrtc::peer_connection::sdp::session_description::RTCSessionDescription;

/// Check if an IP address is private (RFC 1918 + others)
fn is_private_ip(ip: &IpAddr) -> bool {
    match ip {
        IpAddr::V4(ipv4) => {
            let octets = ipv4.octets();
            // 10.0.0.0/8
            octets[0] == 10
            // 172.16.0.0/12
            || (octets[0] == 172 && (octets[1] >= 16 && octets[1] < 32))
            // 192.168.0.0/16
            || (octets[0] == 192 && octets[1] == 168)
            // 127.0.0.0/8 (loopback)
            || octets[0] == 127
            // 169.254.0.0/16 (link-local)
            || (octets[0] == 169 && octets[1] == 254)
            // 0.0.0.0/8 (current network)
            || octets[0] == 0
        }
        IpAddr::V6(ipv6) => {
            // ::1 (loopback)
            ipv6.is_loopback()
            // fe80::/10 (link-local)
            || (ipv6.segments()[0] & 0xffc0) == 0xfe80
            // fc00::/7 (unique local)
            || (ipv6.segments()[0] & 0xfe00) == 0xfc00
            // :: (unspecified)
            || ipv6.is_unspecified()
        }
    }
}

/// Filter ICE candidate to only send safe candidates to clients.
///
/// **Security Issue (#21)**: Prevents leaking internal network topology by filtering:
/// - Private IP addresses (RFC 1918: 10.x.x.x, 172.16.x.x, 192.168.x.x)
/// - Link-local addresses (169.254.x.x)
/// - Loopback addresses (127.x.x.x)
///
/// Only sends:
/// - SRFLX (server reflexive) candidates from STUN
/// - RELAY candidates from TURN
///
/// Returns `None` if the candidate should be filtered (not sent to client).
fn filter_ice_candidate(candidate: &RTCIceCandidate) -> Option<RTCIceCandidate> {
    let candidate_type = candidate.typ.to_string().to_lowercase();

    // Always allow reflexive and relay candidates (from STUN/TURN)
    if candidate_type == "srflx" || candidate_type == "relay" {
        return Some(candidate.clone());
    }

    // For host candidates, check if the address is private
    if candidate_type == "host" {
        // Parse the address from candidate string
        let addr_str = &candidate.address;
        if !addr_str.is_empty() {
            if let Ok(ip) = addr_str.parse::<IpAddr>() {
                if !is_private_ip(&ip) {
                    // Public host candidate - allow it
                    return Some(candidate.clone());
                } else {
                    debug!(
                        address = %addr_str,
                        "Filtered private host ICE candidate"
                    );
                    return None;
                }
            }
        }

        // If we can't parse the address, filter it to be safe
        debug!("Filtered unparseable host ICE candidate");
        return None;
    }

    // Filter unknown candidate types for security
    debug!(
        candidate_type = %candidate_type,
        "Filtered unknown ICE candidate type"
    );
    None
}

/// Events generated by the SFU that need to be sent back through the signaling channel
#[derive(Debug)]
pub enum SfuSignalingEvent {
    /// An ICE candidate generated by the server-side PeerConnection
    IceCandidate {
        peer_id: String,
        candidate_json: String,
    },
    /// A new SDP offer/answer from the server (e.g., after renegotiation)
    SdpAnswer {
        peer_id: String,
        sdp: String,
    },
    /// SFU migration offer for an existing P2P peer
    MigrationOffer {
        migration_id: String,
        sdp: String,
    },
}

/// Migration state for a single peer
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PeerMigrationState {
    /// Server-side PeerConnection created, offer sent to client
    Migrating,
    /// Client answered, ICE completed, media flowing through SFU
    Completed,
    /// Migration failed (timeout or error), peer remains in P2P mode
    Failed,
}

/// Result of initiating migration for a single peer
#[derive(Debug)]
pub struct PeerMigrationResult {
    /// Connection ID of the peer
    pub conn_id: String,
    /// SDP offer JSON to send to the peer
    pub sdp_offer: String,
    /// Signaling event receiver for ICE candidates etc.
    pub event_rx: mpsc::UnboundedReceiver<SfuSignalingEvent>,
}

/// Per-session state for an SFU peer connection
struct SfuSession {
    /// The server-side PeerConnection
    pc: Arc<PeerConnection>,
    /// SFU room reference (held to keep the room alive while the session exists)
    #[allow(dead_code)]
    room: Arc<SfuRoom>,
    /// SFU peer reference (needed for RTCP handler and bandwidth estimation)
    sfu_peer: Arc<SfuPeer>,
    /// RTCP handler task (polls stats for bandwidth estimation)
    #[allow(dead_code)]
    rtcp_task: Option<JoinHandle<()>>,
    /// RTCP handler (held for cancellation on drop)
    #[allow(dead_code)]
    rtcp_handler: Option<RtcpHandler>,
    /// Last activity timestamp for idle timeout detection
    last_activity: Arc<parking_lot::Mutex<Instant>>,
    /// Connection ID for logging
    conn_id: String,
    /// Room ID for cleanup
    room_id: String,
    /// Peer ID for cleanup
    peer_id: String,
}

/// SFU Session Manager - manages server-side PeerConnections for rooms in SFU mode
pub struct SfuSessionManager {
    /// SFU manager for room/peer management
    sfu_manager: Arc<SfuManager>,

    /// ICE server manager
    ice_manager: Arc<IceManager>,

    /// Active sessions: connection_id -> SfuSession (Arc-wrapped for sharing with callbacks)
    sessions: Arc<DashMap<String, SfuSession>>,

    /// Cleanup task cancellation token
    cleanup_cancel_token: CancellationToken,

    /// Session idle timeout (connections with no RTCP stats for this duration are closed)
    session_idle_timeout: Duration,
}

impl SfuSessionManager {
    /// Create a new SFU session manager with default 5-minute idle timeout
    pub fn new(sfu_manager: Arc<SfuManager>, ice_manager: Arc<IceManager>) -> Arc<Self> {
        Self::with_timeout(sfu_manager, ice_manager, Duration::from_secs(300))
    }

    /// Create a new SFU session manager with custom idle timeout
    pub fn with_timeout(
        sfu_manager: Arc<SfuManager>,
        ice_manager: Arc<IceManager>,
        session_idle_timeout: Duration,
    ) -> Arc<Self> {
        let manager = Arc::new(Self {
            sfu_manager,
            ice_manager,
            sessions: Arc::new(DashMap::new()),
            cleanup_cancel_token: CancellationToken::new(),
            session_idle_timeout,
        });

        // Start background cleanup task
        Self::start_cleanup_task(Arc::clone(&manager));

        manager
    }

    /// Start background task to clean up idle sessions
    fn start_cleanup_task(manager: Arc<Self>) {
        let cancel_token = manager.cleanup_cancel_token.clone();
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(Duration::from_secs(60));
            loop {
                tokio::select! {
                    () = cancel_token.cancelled() => {
                        info!("SFU session cleanup task cancelled");
                        break;
                    }
                    _ = interval.tick() => {
                        manager.cleanup_idle_sessions().await;
                    }
                }
            }
        });
    }

    /// Clean up idle sessions that have exceeded the timeout
    async fn cleanup_idle_sessions(&self) {
        let now = Instant::now();
        let mut expired_sessions = Vec::new();

        // Identify expired sessions
        for entry in self.sessions.iter() {
            let (conn_id, session) = (entry.key(), entry.value());
            let last_activity = *session.last_activity.lock();
            let idle_duration = now.duration_since(last_activity);

            if idle_duration > self.session_idle_timeout {
                warn!(
                    conn_id = %conn_id,
                    idle_duration_secs = idle_duration.as_secs(),
                    timeout_secs = self.session_idle_timeout.as_secs(),
                    "SFU session idle timeout, marking for cleanup"
                );
                expired_sessions.push((
                    conn_id.clone(),
                    session.room_id.clone(),
                    session.peer_id.clone(),
                ));
            }
        }

        // Remove expired sessions
        for (conn_id, room_id, peer_id) in expired_sessions {
            if let Err(e) = self.remove_session(&conn_id, &room_id, &peer_id).await {
                error!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to clean up idle SFU session"
                );
            }
        }
    }

    /// Check whether a room should use SFU mode based on the current RTC peer count
    pub fn should_use_sfu(&self, rtc_peer_count: usize) -> bool {
        rtc_peer_count >= self.sfu_manager.config().sfu_threshold
    }

    /// Get the SFU threshold from config
    pub fn sfu_threshold(&self) -> usize {
        self.sfu_manager.config().sfu_threshold
    }

    /// Create an SFU session for a peer.
    ///
    /// This creates a server-side `PeerConnection`, registers the peer with the
    /// SFU room, and sets up track/ICE callbacks.
    ///
    /// Returns an `UnboundedReceiver` for signaling events (ICE candidates, etc.)
    /// that must be forwarded to the client.
    pub async fn create_session(
        &self,
        room_id: &str,
        peer_id: &str,
        conn_id: &str,
    ) -> Result<mpsc::UnboundedReceiver<SfuSignalingEvent>> {
        let sfu_room_id = RoomId::from(room_id);
        let sfu_peer_id = PeerId::from(peer_id);

        // Get or create the SFU room
        let room = self
            .sfu_manager
            .get_or_create_room(sfu_room_id.clone())
            .await?;

        // Register the peer with the room
        let sfu_peer = room
            .add_peer(sfu_peer_id.clone(), self.sfu_manager.config().max_peers_per_room)
            .await?;

        // Get ICE servers
        let ice_servers = self.ice_manager.get_servers().await;

        // Create server-side PeerConnection
        let pc = PeerConnection::new(
            sfu_peer_id.clone(),
            sfu_room_id.clone(),
            ice_servers,
        )
        .await?;
        let pc = Arc::new(pc);

        // Create signaling event channel
        let (event_tx, event_rx) = mpsc::unbounded_channel();

        // Set up callbacks with room integration
        let room_for_track = Arc::clone(&room);
        let peer_id_for_track = sfu_peer_id.clone();
        let room_id_for_track = sfu_room_id.clone();
        let sessions_for_track = Arc::clone(&self.sessions);
        let event_tx_for_ice = event_tx.clone();
        let peer_id_str = peer_id.to_string();

        // on_track: register incoming tracks with the SFU room, then create
        // outbound tracks on all other subscribers' PeerConnections so they
        // can receive the newly published media.
        pc.pc.on_track(Box::new(
            move |remote_track: Arc<webrtc::track::track_remote::TrackRemote>,
                  rtp_receiver: Arc<webrtc::rtp_transceiver::rtp_receiver::RTCRtpReceiver>,
                  _transceiver: Arc<webrtc::rtp_transceiver::RTCRtpTransceiver>| {
                let room = Arc::clone(&room_for_track);
                let peer_id = peer_id_for_track.clone();
                let room_id = room_id_for_track.clone();
                let sessions = sessions_for_track.clone();
                Box::pin(async move {
                    let track_id = TrackId::from(remote_track.id());
                    let kind = TrackKind::from(remote_track.kind());
                    let codec = remote_track.codec().capability.mime_type.clone();

                    info!(
                        peer_id = %peer_id,
                        room_id = %room_id,
                        track_id = %track_id,
                        kind = ?kind,
                        codec = %codec,
                        "SFU: Received new track from peer"
                    );

                    let media_track = Arc::new(MediaTrack::new(
                        track_id.clone(),
                        peer_id.clone(),
                        remote_track,
                        rtp_receiver,
                    ));

                    // Set initial simulcast quality layer for video tracks
                    if kind == TrackKind::Video {
                        media_track.set_quality_layer(crate::track::QualityLayer::Medium);
                    }

                    if let Err(e) = room
                        .add_published_track(&peer_id, track_id.clone(), media_track)
                        .await
                    {
                        error!(
                            peer_id = %peer_id,
                            track_id = %track_id,
                            error = %e,
                            "SFU: Failed to register track with room"
                        );
                        return;
                    }

                    // Add outbound track to all other peers' PeerConnections
                    // so they can receive this newly published track.
                    for entry in sessions.iter() {
                        let session = entry.value();
                        // Skip the publisher itself
                        if session.peer_id == peer_id.as_str() {
                            continue;
                        }
                        if let Err(e) = session
                            .pc
                            .add_outbound_track(track_id.clone(), kind, &codec)
                            .await
                        {
                            warn!(
                                subscriber_peer = %session.peer_id,
                                track_id = %track_id,
                                error = %e,
                                "SFU: Failed to add outbound track to subscriber"
                            );
                        } else {
                            // Subscribe the peer to the track in the room
                            let subscriber_peer_id = PeerId::from(session.peer_id.as_str());
                            if let Err(e) = room
                                .subscribe_track(&subscriber_peer_id, &track_id)
                                .await
                            {
                                warn!(
                                    subscriber_peer = %session.peer_id,
                                    track_id = %track_id,
                                    error = %e,
                                    "SFU: Failed to subscribe peer to track"
                                );
                            }
                        }
                    }
                })
            },
        ));

        // on_ice_candidate: send candidates back through the signaling channel
        // Apply filtering to prevent leaking internal network topology
        pc.pc.on_ice_candidate(Box::new(move |candidate: Option<RTCIceCandidate>| {
            let event_tx = event_tx_for_ice.clone();
            let peer_id = peer_id_str.clone();
            Box::pin(async move {
                if let Some(candidate) = candidate {
                    // Filter candidate for security (only send reflexive/relay, not private IPs)
                    let filtered_candidate = filter_ice_candidate(&candidate);
                    if filtered_candidate.is_none() {
                        debug!(
                            peer_id = %peer_id,
                            candidate_type = %candidate.typ,
                            "ICE candidate filtered (security)"
                        );
                        return;
                    }

                    let candidate_json = match candidate.to_json() {
                        Ok(init) => match serde_json::to_string(&init) {
                            Ok(json) => json,
                            Err(e) => {
                                warn!(error = %e, "Failed to serialize ICE candidate");
                                return;
                            }
                        },
                        Err(e) => {
                            warn!(error = %e, "Failed to convert ICE candidate to JSON");
                            return;
                        }
                    };

                    debug!(
                        peer_id = %peer_id,
                        candidate_type = %candidate.typ,
                        "SFU: Sending filtered ICE candidate to signaling channel"
                    );

                    if event_tx
                        .send(SfuSignalingEvent::IceCandidate {
                            peer_id: peer_id.clone(),
                            candidate_json,
                        })
                        .is_err()
                    {
                        debug!(peer_id = %peer_id, "SFU: Signaling event channel closed");
                    }
                }
            })
        }));

        // Set up connection state monitoring
        let network_monitor = room.network_monitor().clone();
        pc.setup_callbacks(network_monitor.clone()).await?;

        // Add outbound tracks for all existing published tracks from other peers.
        // This ensures the new subscriber can receive media that is already being
        // published in the room.
        let existing_tracks = room.get_published_track_info();
        let mut outbound_count: usize = 0;
        for (track_id, publisher_peer_id, kind, codec) in existing_tracks.iter() {
            // Skip tracks published by this peer (they are inbound, not outbound)
            if *publisher_peer_id == sfu_peer_id {
                continue;
            }
            let tid: TrackId = track_id.clone();
            if let Err(e) = pc.add_outbound_track(tid, *kind, codec.as_str()).await {
                warn!(
                    peer_id = %sfu_peer_id,
                    track_id = %track_id,
                    error = %e,
                    "SFU: Failed to add outbound track for existing published track"
                );
            } else {
                outbound_count += 1;
                // Subscribe in the room so forwarding includes this peer
                if let Err(e) = room.subscribe_track(&sfu_peer_id, track_id).await {
                    warn!(
                        peer_id = %sfu_peer_id,
                        track_id = %track_id,
                        error = %e,
                        "SFU: Failed to subscribe to existing track"
                    );
                }
            }
        }

        // Start RTCP handler for bandwidth estimation and network quality monitoring
        let rtcp_handler = RtcpHandler::new(
            sfu_peer_id.clone(),
            network_monitor,
            Arc::clone(&sfu_peer),
        );
        let rtcp_task = match rtcp_handler.start(Arc::clone(&pc.pc), vec![]).await {
            Ok(handle) => Some(handle),
            Err(e) => {
                warn!(
                    peer_id = %sfu_peer_id,
                    error = %e,
                    "SFU: Failed to start RTCP handler, continuing without bandwidth estimation"
                );
                None
            }
        };

        // Store session with initial activity timestamp
        self.sessions.insert(
            conn_id.to_string(),
            SfuSession {
                pc: Arc::clone(&pc),
                room: Arc::clone(&room),
                sfu_peer: Arc::clone(&sfu_peer),
                rtcp_task,
                rtcp_handler: Some(rtcp_handler),
                last_activity: Arc::new(parking_lot::Mutex::new(Instant::now())),
                conn_id: conn_id.to_string(),
                room_id: room_id.to_string(),
                peer_id: peer_id.to_string(),
            },
        );

        // Start subscriber output for this peer
        pc.start_subscriber_output(sfu_peer).await?;

        info!(
            room_id = %room_id,
            peer_id = %peer_id,
            conn_id = %conn_id,
            outbound_track_count = outbound_count,
            "SFU session created"
        );

        Ok(event_rx)
    }

    /// Handle an SDP offer from the client, returning the server's SDP answer
    pub async fn handle_offer(
        &self,
        conn_id: &str,
        sdp_json: &str,
    ) -> Result<String> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        // Parse the SDP offer
        let offer: RTCSessionDescription = serde_json::from_str(sdp_json)
            .map_err(|e| anyhow!("Invalid SDP offer JSON: {}", e))?;

        // Generate answer
        let answer = session.pc.handle_offer(offer).await?;

        // Serialize answer
        let answer_json = serde_json::to_string(&answer)
            .map_err(|e| anyhow!("Failed to serialize SDP answer: {}", e))?;

        // Update activity timestamp
        drop(session);
        self.touch_session(conn_id);

        Ok(answer_json)
    }

    /// Handle an ICE candidate from the client
    pub async fn add_ice_candidate(
        &self,
        conn_id: &str,
        candidate_json: &str,
    ) -> Result<()> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        let candidate_init: webrtc::ice_transport::ice_candidate::RTCIceCandidateInit =
            serde_json::from_str(candidate_json)
                .map_err(|e| anyhow!("Invalid ICE candidate JSON: {}", e))?;

        session.pc.add_ice_candidate(candidate_init).await?;

        // Update activity timestamp
        drop(session);
        self.touch_session(conn_id);

        Ok(())
    }

    /// Update activity timestamp for a session (prevents idle timeout)
    fn touch_session(&self, conn_id: &str) {
        if let Some(session) = self.sessions.get(conn_id) {
            *session.last_activity.lock() = Instant::now();
        }
    }

    /// Check if a connection has an active SFU session
    pub fn has_session(&self, conn_id: &str) -> bool {
        self.sessions.contains_key(conn_id)
    }

    /// Remove an SFU session and clean up resources
    pub async fn remove_session(
        &self,
        conn_id: &str,
        room_id: &str,
        peer_id: &str,
    ) -> Result<()> {
        if let Some((_, session)) = self.sessions.remove(conn_id) {
            // Close the PeerConnection
            if let Err(e) = session.pc.close().await {
                warn!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to close SFU PeerConnection"
                );
            }

            // Remove the peer from the SFU room
            let sfu_room_id = RoomId::from(room_id);
            let sfu_peer_id = PeerId::from(peer_id);
            if let Err(e) = self
                .sfu_manager
                .remove_peer_from_room(&sfu_room_id, &sfu_peer_id)
                .await
            {
                warn!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to remove peer from SFU room"
                );
            }

            info!(
                room_id = %room_id,
                peer_id = %peer_id,
                conn_id = %conn_id,
                "SFU session removed"
            );
        }

        Ok(())
    }

    /// Get the number of active SFU sessions
    pub fn session_count(&self) -> usize {
        self.sessions.len()
    }

    /// Create an SFU session for an existing P2P peer during migration.
    ///
    /// Unlike `create_session`, this creates a server-side `PeerConnection` and
    /// generates an SDP offer (rather than waiting for the client to send one).
    /// The client will respond with an SDP answer via `SfuMigrationAnswer`.
    ///
    /// Returns the SDP offer and a signaling event receiver, or an error if
    /// session creation fails.
    pub async fn create_migration_session(
        &self,
        room_id: &str,
        peer_id: &str,
        conn_id: &str,
    ) -> Result<PeerMigrationResult> {
        let sfu_room_id = RoomId::from(room_id);
        let sfu_peer_id = PeerId::from(peer_id);

        // Get or create the SFU room
        let room = self
            .sfu_manager
            .get_or_create_room(sfu_room_id.clone())
            .await?;

        // Register the peer with the room
        let sfu_peer = room
            .add_peer(sfu_peer_id.clone(), self.sfu_manager.config().max_peers_per_room)
            .await?;

        // Get ICE servers
        let ice_servers = self.ice_manager.get_servers().await;

        // Create server-side PeerConnection
        let pc = PeerConnection::new(
            sfu_peer_id.clone(),
            sfu_room_id.clone(),
            ice_servers,
        )
        .await?;
        let pc = Arc::new(pc);

        // Create signaling event channel
        let (event_tx, event_rx) = mpsc::unbounded_channel();

        // Set up callbacks with room integration
        let room_for_track = Arc::clone(&room);
        let peer_id_for_track = sfu_peer_id.clone();
        let room_id_for_track = sfu_room_id.clone();
        let sessions_for_track = Arc::clone(&self.sessions);
        let event_tx_for_ice = event_tx.clone();
        let peer_id_str = peer_id.to_string();

        // on_track: register incoming tracks with the SFU room, then create
        // outbound tracks on all other subscribers' PeerConnections so they
        // can receive the newly published media.
        pc.pc.on_track(Box::new(
            move |remote_track: Arc<webrtc::track::track_remote::TrackRemote>,
                  rtp_receiver: Arc<webrtc::rtp_transceiver::rtp_receiver::RTCRtpReceiver>,
                  _transceiver: Arc<webrtc::rtp_transceiver::RTCRtpTransceiver>| {
                let room = Arc::clone(&room_for_track);
                let peer_id = peer_id_for_track.clone();
                let room_id = room_id_for_track.clone();
                let sessions = sessions_for_track.clone();
                Box::pin(async move {
                    let track_id = TrackId::from(remote_track.id());
                    let kind = TrackKind::from(remote_track.kind());
                    let codec = remote_track.codec().capability.mime_type.clone();

                    info!(
                        peer_id = %peer_id,
                        room_id = %room_id,
                        track_id = %track_id,
                        kind = ?kind,
                        codec = %codec,
                        "SFU migration: Received track from migrating peer"
                    );

                    let media_track = Arc::new(MediaTrack::new(
                        track_id.clone(),
                        peer_id.clone(),
                        remote_track,
                        rtp_receiver,
                    ));

                    // Set initial simulcast quality layer for video tracks
                    if kind == TrackKind::Video {
                        media_track.set_quality_layer(crate::track::QualityLayer::Medium);
                    }

                    if let Err(e) = room
                        .add_published_track(&peer_id, track_id.clone(), media_track)
                        .await
                    {
                        error!(
                            peer_id = %peer_id,
                            track_id = %track_id,
                            error = %e,
                            "SFU migration: Failed to register track with room"
                        );
                        return;
                    }

                    // Add outbound track to all other peers' PeerConnections
                    // so they can receive this newly published track.
                    for entry in sessions.iter() {
                        let session = entry.value();
                        // Skip the publisher itself
                        if session.peer_id == peer_id.as_str() {
                            continue;
                        }
                        if let Err(e) = session
                            .pc
                            .add_outbound_track(track_id.clone(), kind, &codec)
                            .await
                        {
                            warn!(
                                subscriber_peer = %session.peer_id,
                                track_id = %track_id,
                                error = %e,
                                "SFU migration: Failed to add outbound track to subscriber"
                            );
                        } else {
                            let subscriber_peer_id = PeerId::from(session.peer_id.as_str());
                            if let Err(e) = room
                                .subscribe_track(&subscriber_peer_id, &track_id)
                                .await
                            {
                                warn!(
                                    subscriber_peer = %session.peer_id,
                                    track_id = %track_id,
                                    error = %e,
                                    "SFU migration: Failed to subscribe peer to track"
                                );
                            }
                        }
                    }
                })
            },
        ));

        // on_ice_candidate: send candidates back through the signaling channel
        // Apply filtering to prevent leaking internal network topology
        pc.pc.on_ice_candidate(Box::new(move |candidate: Option<RTCIceCandidate>| {
            let event_tx = event_tx_for_ice.clone();
            let peer_id = peer_id_str.clone();
            Box::pin(async move {
                if let Some(candidate) = candidate {
                    // Filter candidate for security (only send reflexive/relay, not private IPs)
                    let filtered_candidate = filter_ice_candidate(&candidate);
                    if filtered_candidate.is_none() {
                        debug!(
                            peer_id = %peer_id,
                            candidate_type = %candidate.typ,
                            "ICE candidate filtered (security)"
                        );
                        return;
                    }

                    let candidate_json = match candidate.to_json() {
                        Ok(init) => match serde_json::to_string(&init) {
                            Ok(json) => json,
                            Err(e) => {
                                warn!(error = %e, "Failed to serialize ICE candidate");
                                return;
                            }
                        },
                        Err(e) => {
                            warn!(error = %e, "Failed to convert ICE candidate to JSON");
                            return;
                        }
                    };

                    debug!(
                        peer_id = %peer_id,
                        candidate_type = %candidate.typ,
                        "SFU migration: Sending filtered ICE candidate to signaling channel"
                    );

                    if event_tx
                        .send(SfuSignalingEvent::IceCandidate {
                            peer_id: peer_id.clone(),
                            candidate_json,
                        })
                        .is_err()
                    {
                        debug!(peer_id = %peer_id, "SFU migration: Signaling event channel closed");
                    }
                }
            })
        }));

        // Set up connection state monitoring
        let network_monitor = room.network_monitor().clone();
        pc.setup_callbacks(network_monitor.clone()).await?;

        // Add outbound tracks for all existing published tracks from other peers.
        // This ensures the migrating subscriber can receive media already being
        // published in the room.
        let existing_tracks = room.get_published_track_info();
        let mut outbound_count: usize = 0;
        for (track_id, publisher_peer_id, kind, codec) in existing_tracks.iter() {
            if *publisher_peer_id == sfu_peer_id {
                continue;
            }
            let tid: TrackId = track_id.clone();
            if let Err(e) = pc.add_outbound_track(tid, *kind, codec.as_str()).await {
                warn!(
                    peer_id = %sfu_peer_id,
                    track_id = %track_id,
                    error = %e,
                    "SFU migration: Failed to add outbound track for existing published track"
                );
            } else {
                outbound_count += 1;
                if let Err(e) = room.subscribe_track(&sfu_peer_id, track_id).await {
                    warn!(
                        peer_id = %sfu_peer_id,
                        track_id = %track_id,
                        error = %e,
                        "SFU migration: Failed to subscribe to existing track"
                    );
                }
            }
        }

        // Create SDP offer from the server side (after adding outbound tracks
        // so they are included in the SDP offer)
        let offer = pc.create_offer().await?;
        let offer_json = serde_json::to_string(&offer)
            .map_err(|e| anyhow!("Failed to serialize SDP offer: {}", e))?;

        // Start RTCP handler for bandwidth estimation and network quality monitoring
        let rtcp_handler = RtcpHandler::new(
            sfu_peer_id.clone(),
            network_monitor,
            Arc::clone(&sfu_peer),
        );
        let rtcp_task = match rtcp_handler.start(Arc::clone(&pc.pc), vec![]).await {
            Ok(handle) => Some(handle),
            Err(e) => {
                warn!(
                    peer_id = %sfu_peer_id,
                    error = %e,
                    "SFU migration: Failed to start RTCP handler, continuing without bandwidth estimation"
                );
                None
            }
        };

        // Store session with initial activity timestamp
        self.sessions.insert(
            conn_id.to_string(),
            SfuSession {
                pc: Arc::clone(&pc),
                room: Arc::clone(&room),
                sfu_peer: Arc::clone(&sfu_peer),
                rtcp_task,
                rtcp_handler: Some(rtcp_handler),
                last_activity: Arc::new(parking_lot::Mutex::new(Instant::now())),
                conn_id: conn_id.to_string(),
                room_id: room_id.to_string(),
                peer_id: peer_id.to_string(),
            },
        );

        // Start subscriber output for this peer
        pc.start_subscriber_output(sfu_peer).await?;

        info!(
            room_id = %room_id,
            peer_id = %peer_id,
            conn_id = %conn_id,
            outbound_track_count = outbound_count,
            "SFU migration session created, offer generated"
        );

        Ok(PeerMigrationResult {
            conn_id: conn_id.to_string(),
            sdp_offer: offer_json,
            event_rx,
        })
    }

    /// Handle an SDP answer from a migrating peer
    pub async fn handle_migration_answer(
        &self,
        conn_id: &str,
        sdp_json: &str,
    ) -> Result<()> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        // Parse the SDP answer
        let answer: RTCSessionDescription = serde_json::from_str(sdp_json)
            .map_err(|e| anyhow!("Invalid SDP answer JSON: {}", e))?;

        // Set remote description (completes the signaling handshake)
        session.pc.handle_answer(answer).await?;

        info!(
            conn_id = %conn_id,
            "SFU migration: answer processed, ICE negotiation in progress"
        );

        // Update activity timestamp
        drop(session);
        self.touch_session(conn_id);

        Ok(())
    }
}

impl Drop for SfuSessionManager {
    fn drop(&mut self) {
        // Cancel cleanup task on drop
        self.cleanup_cancel_token.cancel();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::SfuConfig;

    #[tokio::test]
    async fn test_should_use_sfu() {
        let config = SfuConfig {
            sfu_threshold: 3,
            ..SfuConfig::default()
        };
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::with_timeout(
            manager,
            ice_manager,
            Duration::from_secs(300),
        );

        assert!(!session_mgr.should_use_sfu(0));
        assert!(!session_mgr.should_use_sfu(1));
        assert!(!session_mgr.should_use_sfu(2));
        assert!(session_mgr.should_use_sfu(3));
        assert!(session_mgr.should_use_sfu(10));
    }

    #[tokio::test]
    async fn test_sfu_threshold() {
        let config = SfuConfig {
            sfu_threshold: 5,
            ..SfuConfig::default()
        };
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::with_timeout(
            manager,
            ice_manager,
            Duration::from_secs(300),
        );

        assert_eq!(session_mgr.sfu_threshold(), 5);
    }

    #[tokio::test]
    async fn test_has_session_empty() {
        let config = SfuConfig::default();
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::with_timeout(
            manager,
            ice_manager,
            Duration::from_secs(300),
        );

        assert!(!session_mgr.has_session("non-existent"));
        assert_eq!(session_mgr.session_count(), 0);
    }

    #[test]
    fn test_is_private_ip_v4() {
        use std::net::Ipv4Addr;

        // Private networks
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1))));
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(172, 16, 0, 1))));
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(192, 168, 1, 1))));

        // Loopback
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1))));

        // Link-local
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(169, 254, 0, 1))));

        // Public IPs
        assert!(!super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(8, 8, 8, 8))));
        assert!(!super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(1, 1, 1, 1))));
    }

    #[test]
    fn test_is_private_ip_v6() {
        use std::net::Ipv6Addr;

        // Loopback
        assert!(super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1))));

        // Link-local
        assert!(super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0xfe80, 0, 0, 0, 0, 0, 0, 1))));

        // Unique local
        assert!(super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0xfc00, 0, 0, 0, 0, 0, 0, 1))));

        // Public
        assert!(!super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0x2001, 0x4860, 0x4860, 0, 0, 0, 0, 0x8888))));
    }

    #[test]
    fn test_filter_ice_candidate_reflexive() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Reflexive candidates should always pass
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Srflx;
        candidate.address = "203.0.113.1".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_some());
    }

    #[test]
    fn test_filter_ice_candidate_relay() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Relay candidates should always pass
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Relay;
        candidate.address = "203.0.113.1".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_some());
    }

    #[test]
    fn test_filter_ice_candidate_private_host() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Private host candidates should be filtered
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Host;
        candidate.address = "192.168.1.1".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_none());
    }

    #[test]
    fn test_filter_ice_candidate_public_host() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Public host candidates should pass
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Host;
        candidate.address = "8.8.8.8".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_some());
    }
}
