//! SFU Session Manager
//!
//! Bridges the API signaling layer with the SFU forwarding plane by managing
//! server-side `PeerConnection` instances. When a room's WebRTC participant
//! count reaches the configured `sfu_threshold`, new peers get a server-side
//! `PeerConnection` instead of pure P2P signaling relay.
//!
//! ## Lifecycle
//!
//! 1. A peer sends a WebRTC Join message
//! 2. The messaging layer checks `should_use_sfu()` against the current RTC peer count
//! 3. If SFU mode is warranted, `create_session()` creates a `PeerConnection` and
//!    registers the peer with the `SfuManager`
//! 4. Subsequent Offer/Answer/ICE messages are routed to the server-side
//!    `PeerConnection` instead of being relayed peer-to-peer
//! 5. When the peer sends WebRTC Leave, `remove_session()` cleans up

use crate::manager::SfuManager;
use crate::room::SfuRoom;
use crate::track::{MediaTrack, TrackKind};
use crate::types::{PeerId, RoomId, TrackId};
use crate::webrtc_control::{IceManager, PeerConnection};
use anyhow::{anyhow, Result};
use dashmap::DashMap;
use std::sync::Arc;
use tokio::sync::mpsc;
use tracing::{debug, error, info, warn};
use webrtc::ice_transport::ice_candidate::RTCIceCandidate;
use webrtc::peer_connection::sdp::session_description::RTCSessionDescription;

/// Events generated by the SFU that need to be sent back through the signaling channel
#[derive(Debug)]
pub enum SfuSignalingEvent {
    /// An ICE candidate generated by the server-side PeerConnection
    IceCandidate {
        peer_id: String,
        candidate_json: String,
    },
    /// A new SDP offer/answer from the server (e.g., after renegotiation)
    SdpAnswer {
        peer_id: String,
        sdp: String,
    },
    /// SFU migration offer for an existing P2P peer
    MigrationOffer {
        migration_id: String,
        sdp: String,
    },
}

/// Migration state for a single peer
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PeerMigrationState {
    /// Server-side PeerConnection created, offer sent to client
    Migrating,
    /// Client answered, ICE completed, media flowing through SFU
    Completed,
    /// Migration failed (timeout or error), peer remains in P2P mode
    Failed,
}

/// Result of initiating migration for a single peer
#[derive(Debug)]
pub struct PeerMigrationResult {
    /// Connection ID of the peer
    pub conn_id: String,
    /// SDP offer JSON to send to the peer
    pub sdp_offer: String,
    /// Signaling event receiver for ICE candidates etc.
    pub event_rx: mpsc::UnboundedReceiver<SfuSignalingEvent>,
}

/// Per-session state for an SFU peer connection
struct SfuSession {
    /// The server-side PeerConnection
    pc: Arc<PeerConnection>,
    /// SFU room reference (held to keep the room alive while the session exists)
    #[allow(dead_code)]
    room: Arc<SfuRoom>,
}

/// SFU Session Manager - manages server-side PeerConnections for rooms in SFU mode
pub struct SfuSessionManager {
    /// SFU manager for room/peer management
    sfu_manager: Arc<SfuManager>,

    /// ICE server manager
    ice_manager: Arc<IceManager>,

    /// Active sessions: connection_id -> SfuSession
    sessions: DashMap<String, SfuSession>,
}

impl SfuSessionManager {
    /// Create a new SFU session manager
    pub fn new(sfu_manager: Arc<SfuManager>, ice_manager: Arc<IceManager>) -> Arc<Self> {
        Arc::new(Self {
            sfu_manager,
            ice_manager,
            sessions: DashMap::new(),
        })
    }

    /// Check whether a room should use SFU mode based on the current RTC peer count
    pub fn should_use_sfu(&self, rtc_peer_count: usize) -> bool {
        rtc_peer_count >= self.sfu_manager.config().sfu_threshold
    }

    /// Get the SFU threshold from config
    pub fn sfu_threshold(&self) -> usize {
        self.sfu_manager.config().sfu_threshold
    }

    /// Create an SFU session for a peer.
    ///
    /// This creates a server-side `PeerConnection`, registers the peer with the
    /// SFU room, and sets up track/ICE callbacks.
    ///
    /// Returns an `UnboundedReceiver` for signaling events (ICE candidates, etc.)
    /// that must be forwarded to the client.
    pub async fn create_session(
        &self,
        room_id: &str,
        peer_id: &str,
        conn_id: &str,
    ) -> Result<mpsc::UnboundedReceiver<SfuSignalingEvent>> {
        let sfu_room_id = RoomId::from(room_id);
        let sfu_peer_id = PeerId::from(peer_id);

        // Get or create the SFU room
        let room = self
            .sfu_manager
            .get_or_create_room(sfu_room_id.clone())
            .await?;

        // Register the peer with the room
        let sfu_peer = room
            .add_peer(sfu_peer_id.clone(), self.sfu_manager.config().max_peers_per_room)
            .await?;

        // Get ICE servers
        let ice_servers = self.ice_manager.get_servers().await;

        // Create server-side PeerConnection
        let pc = PeerConnection::new(
            sfu_peer_id.clone(),
            sfu_room_id.clone(),
            ice_servers,
        )
        .await?;
        let pc = Arc::new(pc);

        // Create signaling event channel
        let (event_tx, event_rx) = mpsc::unbounded_channel();

        // Set up callbacks with room integration
        let room_for_track = Arc::clone(&room);
        let peer_id_for_track = sfu_peer_id.clone();
        let room_id_for_track = sfu_room_id.clone();
        let event_tx_for_ice = event_tx.clone();
        let peer_id_str = peer_id.to_string();

        // on_track: register incoming tracks with the SFU room
        pc.pc.on_track(Box::new(
            move |remote_track: Arc<webrtc::track::track_remote::TrackRemote>,
                  rtp_receiver: Arc<webrtc::rtp_transceiver::rtp_receiver::RTCRtpReceiver>,
                  _transceiver: Arc<webrtc::rtp_transceiver::RTCRtpTransceiver>| {
                let room = Arc::clone(&room_for_track);
                let peer_id = peer_id_for_track.clone();
                let room_id = room_id_for_track.clone();
                Box::pin(async move {
                    let track_id = TrackId::from(remote_track.id());
                    let kind = TrackKind::from(remote_track.kind());

                    info!(
                        peer_id = %peer_id,
                        room_id = %room_id,
                        track_id = %track_id,
                        kind = ?kind,
                        "SFU: Received new track from peer"
                    );

                    let media_track = Arc::new(MediaTrack::new(
                        track_id.clone(),
                        peer_id.clone(),
                        remote_track,
                        rtp_receiver,
                    ));

                    if let Err(e) = room
                        .add_published_track(&peer_id, track_id.clone(), media_track)
                        .await
                    {
                        error!(
                            peer_id = %peer_id,
                            track_id = %track_id,
                            error = %e,
                            "SFU: Failed to register track with room"
                        );
                    }
                })
            },
        ));

        // on_ice_candidate: send candidates back through the signaling channel
        pc.pc.on_ice_candidate(Box::new(move |candidate: Option<RTCIceCandidate>| {
            let event_tx = event_tx_for_ice.clone();
            let peer_id = peer_id_str.clone();
            Box::pin(async move {
                if let Some(candidate) = candidate {
                    let candidate_json = match candidate.to_json() {
                        Ok(init) => match serde_json::to_string(&init) {
                            Ok(json) => json,
                            Err(e) => {
                                warn!(error = %e, "Failed to serialize ICE candidate");
                                return;
                            }
                        },
                        Err(e) => {
                            warn!(error = %e, "Failed to convert ICE candidate to JSON");
                            return;
                        }
                    };

                    debug!(
                        peer_id = %peer_id,
                        "SFU: Sending ICE candidate to signaling channel"
                    );

                    if event_tx
                        .send(SfuSignalingEvent::IceCandidate {
                            peer_id: peer_id.clone(),
                            candidate_json,
                        })
                        .is_err()
                    {
                        debug!(peer_id = %peer_id, "SFU: Signaling event channel closed");
                    }
                }
            })
        }));

        // Set up connection state monitoring
        let network_monitor = room.network_monitor().clone();
        pc.setup_callbacks(network_monitor).await?;

        // Store session
        self.sessions.insert(
            conn_id.to_string(),
            SfuSession {
                pc: Arc::clone(&pc),
                room: Arc::clone(&room),
            },
        );

        // Start subscriber output for this peer
        pc.start_subscriber_output(sfu_peer).await?;

        info!(
            room_id = %room_id,
            peer_id = %peer_id,
            conn_id = %conn_id,
            "SFU session created"
        );

        Ok(event_rx)
    }

    /// Handle an SDP offer from the client, returning the server's SDP answer
    pub async fn handle_offer(
        &self,
        conn_id: &str,
        sdp_json: &str,
    ) -> Result<String> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        // Parse the SDP offer
        let offer: RTCSessionDescription = serde_json::from_str(sdp_json)
            .map_err(|e| anyhow!("Invalid SDP offer JSON: {}", e))?;

        // Generate answer
        let answer = session.pc.handle_offer(offer).await?;

        // Serialize answer
        let answer_json = serde_json::to_string(&answer)
            .map_err(|e| anyhow!("Failed to serialize SDP answer: {}", e))?;

        Ok(answer_json)
    }

    /// Handle an ICE candidate from the client
    pub async fn add_ice_candidate(
        &self,
        conn_id: &str,
        candidate_json: &str,
    ) -> Result<()> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        let candidate_init: webrtc::ice_transport::ice_candidate::RTCIceCandidateInit =
            serde_json::from_str(candidate_json)
                .map_err(|e| anyhow!("Invalid ICE candidate JSON: {}", e))?;

        session.pc.add_ice_candidate(candidate_init).await?;

        Ok(())
    }

    /// Check if a connection has an active SFU session
    pub fn has_session(&self, conn_id: &str) -> bool {
        self.sessions.contains_key(conn_id)
    }

    /// Remove an SFU session and clean up resources
    pub async fn remove_session(
        &self,
        conn_id: &str,
        room_id: &str,
        peer_id: &str,
    ) -> Result<()> {
        if let Some((_, session)) = self.sessions.remove(conn_id) {
            // Close the PeerConnection
            if let Err(e) = session.pc.close().await {
                warn!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to close SFU PeerConnection"
                );
            }

            // Remove the peer from the SFU room
            let sfu_room_id = RoomId::from(room_id);
            let sfu_peer_id = PeerId::from(peer_id);
            if let Err(e) = self
                .sfu_manager
                .remove_peer_from_room(&sfu_room_id, &sfu_peer_id)
                .await
            {
                warn!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to remove peer from SFU room"
                );
            }

            info!(
                room_id = %room_id,
                peer_id = %peer_id,
                conn_id = %conn_id,
                "SFU session removed"
            );
        }

        Ok(())
    }

    /// Get the number of active SFU sessions
    pub fn session_count(&self) -> usize {
        self.sessions.len()
    }

    /// Create an SFU session for an existing P2P peer during migration.
    ///
    /// Unlike `create_session`, this creates a server-side `PeerConnection` and
    /// generates an SDP offer (rather than waiting for the client to send one).
    /// The client will respond with an SDP answer via `SfuMigrationAnswer`.
    ///
    /// Returns the SDP offer and a signaling event receiver, or an error if
    /// session creation fails.
    pub async fn create_migration_session(
        &self,
        room_id: &str,
        peer_id: &str,
        conn_id: &str,
    ) -> Result<PeerMigrationResult> {
        let sfu_room_id = RoomId::from(room_id);
        let sfu_peer_id = PeerId::from(peer_id);

        // Get or create the SFU room
        let room = self
            .sfu_manager
            .get_or_create_room(sfu_room_id.clone())
            .await?;

        // Register the peer with the room
        let sfu_peer = room
            .add_peer(sfu_peer_id.clone(), self.sfu_manager.config().max_peers_per_room)
            .await?;

        // Get ICE servers
        let ice_servers = self.ice_manager.get_servers().await;

        // Create server-side PeerConnection
        let pc = PeerConnection::new(
            sfu_peer_id.clone(),
            sfu_room_id.clone(),
            ice_servers,
        )
        .await?;
        let pc = Arc::new(pc);

        // Create signaling event channel
        let (event_tx, event_rx) = mpsc::unbounded_channel();

        // Set up callbacks with room integration
        let room_for_track = Arc::clone(&room);
        let peer_id_for_track = sfu_peer_id.clone();
        let room_id_for_track = sfu_room_id.clone();
        let event_tx_for_ice = event_tx.clone();
        let peer_id_str = peer_id.to_string();

        // on_track: register incoming tracks with the SFU room
        pc.pc.on_track(Box::new(
            move |remote_track: Arc<webrtc::track::track_remote::TrackRemote>,
                  rtp_receiver: Arc<webrtc::rtp_transceiver::rtp_receiver::RTCRtpReceiver>,
                  _transceiver: Arc<webrtc::rtp_transceiver::RTCRtpTransceiver>| {
                let room = Arc::clone(&room_for_track);
                let peer_id = peer_id_for_track.clone();
                let room_id = room_id_for_track.clone();
                Box::pin(async move {
                    let track_id = TrackId::from(remote_track.id());
                    let kind = TrackKind::from(remote_track.kind());

                    info!(
                        peer_id = %peer_id,
                        room_id = %room_id,
                        track_id = %track_id,
                        kind = ?kind,
                        "SFU migration: Received track from migrating peer"
                    );

                    let media_track = Arc::new(MediaTrack::new(
                        track_id.clone(),
                        peer_id.clone(),
                        remote_track,
                        rtp_receiver,
                    ));

                    if let Err(e) = room
                        .add_published_track(&peer_id, track_id.clone(), media_track)
                        .await
                    {
                        error!(
                            peer_id = %peer_id,
                            track_id = %track_id,
                            error = %e,
                            "SFU migration: Failed to register track with room"
                        );
                    }
                })
            },
        ));

        // on_ice_candidate: send candidates back through the signaling channel
        pc.pc.on_ice_candidate(Box::new(move |candidate: Option<RTCIceCandidate>| {
            let event_tx = event_tx_for_ice.clone();
            let peer_id = peer_id_str.clone();
            Box::pin(async move {
                if let Some(candidate) = candidate {
                    let candidate_json = match candidate.to_json() {
                        Ok(init) => match serde_json::to_string(&init) {
                            Ok(json) => json,
                            Err(e) => {
                                warn!(error = %e, "Failed to serialize ICE candidate");
                                return;
                            }
                        },
                        Err(e) => {
                            warn!(error = %e, "Failed to convert ICE candidate to JSON");
                            return;
                        }
                    };

                    debug!(
                        peer_id = %peer_id,
                        "SFU migration: Sending ICE candidate to signaling channel"
                    );

                    if event_tx
                        .send(SfuSignalingEvent::IceCandidate {
                            peer_id: peer_id.clone(),
                            candidate_json,
                        })
                        .is_err()
                    {
                        debug!(peer_id = %peer_id, "SFU migration: Signaling event channel closed");
                    }
                }
            })
        }));

        // Set up connection state monitoring
        let network_monitor = room.network_monitor().clone();
        pc.setup_callbacks(network_monitor).await?;

        // Create SDP offer from the server side
        let offer = pc.create_offer().await?;
        let offer_json = serde_json::to_string(&offer)
            .map_err(|e| anyhow!("Failed to serialize SDP offer: {}", e))?;

        // Store session
        self.sessions.insert(
            conn_id.to_string(),
            SfuSession {
                pc: Arc::clone(&pc),
                room: Arc::clone(&room),
            },
        );

        // Start subscriber output for this peer
        pc.start_subscriber_output(sfu_peer).await?;

        info!(
            room_id = %room_id,
            peer_id = %peer_id,
            conn_id = %conn_id,
            "SFU migration session created, offer generated"
        );

        Ok(PeerMigrationResult {
            conn_id: conn_id.to_string(),
            sdp_offer: offer_json,
            event_rx,
        })
    }

    /// Handle an SDP answer from a migrating peer
    pub async fn handle_migration_answer(
        &self,
        conn_id: &str,
        sdp_json: &str,
    ) -> Result<()> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        // Parse the SDP answer
        let answer: RTCSessionDescription = serde_json::from_str(sdp_json)
            .map_err(|e| anyhow!("Invalid SDP answer JSON: {}", e))?;

        // Set remote description (completes the signaling handshake)
        session.pc.handle_answer(answer).await?;

        info!(
            conn_id = %conn_id,
            "SFU migration: answer processed, ICE negotiation in progress"
        );

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::SfuConfig;

    #[tokio::test]
    async fn test_should_use_sfu() {
        let config = SfuConfig {
            sfu_threshold: 3,
            ..SfuConfig::default()
        };
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::new(manager, ice_manager);

        assert!(!session_mgr.should_use_sfu(0));
        assert!(!session_mgr.should_use_sfu(1));
        assert!(!session_mgr.should_use_sfu(2));
        assert!(session_mgr.should_use_sfu(3));
        assert!(session_mgr.should_use_sfu(10));
    }

    #[tokio::test]
    async fn test_sfu_threshold() {
        let config = SfuConfig {
            sfu_threshold: 5,
            ..SfuConfig::default()
        };
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::new(manager, ice_manager);

        assert_eq!(session_mgr.sfu_threshold(), 5);
    }

    #[tokio::test]
    async fn test_has_session_empty() {
        let config = SfuConfig::default();
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::new(manager, ice_manager);

        assert!(!session_mgr.has_session("non-existent"));
        assert_eq!(session_mgr.session_count(), 0);
    }
}
