//! SFU Session Manager
//!
//! Bridges the API signaling layer with the SFU forwarding plane by managing
//! server-side `PeerConnection` instances. When a room's WebRTC participant
//! count reaches the configured `sfu_threshold`, new peers get a server-side
//! `PeerConnection` instead of pure P2P signaling relay.
//!
//! ## Lifecycle
//!
//! 1. A peer sends a WebRTC Join message
//! 2. The messaging layer checks `should_use_sfu()` against the current RTC peer count
//! 3. If SFU mode is warranted, `create_session()` creates a `PeerConnection` and
//!    registers the peer with the `SfuManager`
//! 4. Subsequent Offer/Answer/ICE messages are routed to the server-side
//!    `PeerConnection` instead of being relayed peer-to-peer
//! 5. When the peer sends WebRTC Leave, `remove_session()` cleans up

use crate::manager::SfuManager;
use crate::peer::SfuPeer;
use crate::room::SfuRoom;
use crate::rtcp_handler::RtcpHandler;
use crate::track::{MediaTrack, TrackKind};
use crate::types::{PeerId, RoomId, TrackId};
use crate::webrtc_control::{IceManager, PeerConnection};
use anyhow::{anyhow, Result};
use dashmap::DashMap;
use std::net::IpAddr;
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::{mpsc, Mutex as TokioMutex};
use tokio::task::JoinHandle;
use tokio_util::sync::CancellationToken;
use tracing::{debug, error, info, warn};
use webrtc::ice_transport::ice_candidate::RTCIceCandidate;
use webrtc::peer_connection::sdp::session_description::RTCSessionDescription;

/// Check if an IP address is private (RFC 1918 + others)
fn is_private_ip(ip: &IpAddr) -> bool {
    match ip {
        IpAddr::V4(ipv4) => {
            let octets = ipv4.octets();
            // 10.0.0.0/8
            octets[0] == 10
            // 172.16.0.0/12
            || (octets[0] == 172 && (octets[1] >= 16 && octets[1] < 32))
            // 192.168.0.0/16
            || (octets[0] == 192 && octets[1] == 168)
            // 127.0.0.0/8 (loopback)
            || octets[0] == 127
            // 169.254.0.0/16 (link-local)
            || (octets[0] == 169 && octets[1] == 254)
            // 0.0.0.0/8 (current network)
            || octets[0] == 0
        }
        IpAddr::V6(ipv6) => {
            // ::1 (loopback)
            ipv6.is_loopback()
            // fe80::/10 (link-local)
            || (ipv6.segments()[0] & 0xffc0) == 0xfe80
            // fc00::/7 (unique local)
            || (ipv6.segments()[0] & 0xfe00) == 0xfc00
            // :: (unspecified)
            || ipv6.is_unspecified()
        }
    }
}

/// Filter ICE candidate to only send safe candidates to clients.
///
/// **Security Issue (#21)**: Prevents leaking internal network topology by filtering:
/// - Private IP addresses (RFC 1918: 10.x.x.x, 172.16.x.x, 192.168.x.x)
/// - Link-local addresses (169.254.x.x)
/// - Loopback addresses (127.x.x.x)
///
/// Only sends:
/// - SRFLX (server reflexive) candidates from STUN
/// - RELAY candidates from TURN
///
/// Returns `None` if the candidate should be filtered (not sent to client).
fn filter_ice_candidate(candidate: &RTCIceCandidate) -> Option<RTCIceCandidate> {
    let candidate_type = candidate.typ.to_string().to_lowercase();

    // Always allow reflexive and relay candidates (from STUN/TURN)
    if candidate_type == "srflx" || candidate_type == "relay" {
        return Some(candidate.clone());
    }

    // For host candidates, check if the address is private
    if candidate_type == "host" {
        // Parse the address from candidate string
        let addr_str = &candidate.address;
        if !addr_str.is_empty() {
            if let Ok(ip) = addr_str.parse::<IpAddr>() {
                if !is_private_ip(&ip) {
                    // Public host candidate - allow it
                    return Some(candidate.clone());
                } else {
                    debug!(
                        address = %addr_str,
                        "Filtered private host ICE candidate"
                    );
                    return None;
                }
            }
        }

        // If we can't parse the address, filter it to be safe
        debug!("Filtered unparseable host ICE candidate");
        return None;
    }

    // Filter unknown candidate types for security
    debug!(
        candidate_type = %candidate_type,
        "Filtered unknown ICE candidate type"
    );
    None
}

/// Events generated by the SFU that need to be sent back through the signaling channel
#[derive(Debug)]
pub enum SfuSignalingEvent {
    /// An ICE candidate generated by the server-side PeerConnection
    IceCandidate {
        peer_id: String,
        candidate_json: String,
    },
    /// A new SDP answer from the server
    SdpAnswer {
        peer_id: String,
        sdp: String,
    },
    /// A new SDP offer from the server (e.g., after renegotiation)
    SdpOffer {
        peer_id: String,
        sdp: String,
    },
    /// An ICE restart offer from the server, sent when ICE enters Failed state.
    /// The client must respond with an SDP answer to complete the ICE restart.
    IceRestartOffer {
        peer_id: String,
        sdp: String,
    },
    /// SFU migration offer for an existing P2P peer
    MigrationOffer {
        migration_id: String,
        sdp: String,
    },
}

/// Migration state for a single peer
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PeerMigrationState {
    /// Server-side PeerConnection created, offer sent to client
    Migrating,
    /// Client answered, ICE completed, media flowing through SFU
    Completed,
    /// Migration failed (timeout or error), peer remains in P2P mode
    Failed,
}

/// Result of initiating migration for a single peer
#[derive(Debug)]
pub struct PeerMigrationResult {
    /// Connection ID of the peer
    pub conn_id: String,
    /// SDP offer JSON to send to the peer
    pub sdp_offer: String,
    /// Signaling event receiver for ICE candidates etc.
    pub event_rx: mpsc::UnboundedReceiver<SfuSignalingEvent>,
}

/// Per-session state for an SFU peer connection
struct SfuSession {
    /// The server-side PeerConnection
    pc: Arc<PeerConnection>,
    /// SFU room reference (held to keep the room alive while the session exists)
    #[allow(dead_code)]
    room: Arc<SfuRoom>,
    /// SFU peer reference (needed for RTCP handler and bandwidth estimation)
    sfu_peer: Arc<SfuPeer>,
    /// RTCP handler task (polls stats for bandwidth estimation)
    #[allow(dead_code)]
    rtcp_task: Option<JoinHandle<()>>,
    /// RTCP handler (held for cancellation on drop)
    #[allow(dead_code)]
    rtcp_handler: Option<RtcpHandler>,
    /// Signaling event sender for SDP renegotiation and ICE candidates.
    /// When a new track is added to a subscriber, the SFU creates a new offer
    /// and sends it through this channel so the API layer forwards it to the client.
    event_tx: mpsc::UnboundedSender<SfuSignalingEvent>,
    /// Last activity timestamp for idle timeout detection
    last_activity: Arc<parking_lot::Mutex<Instant>>,
    /// Per-peer renegotiation lock.
    /// Prevents concurrent SDP renegotiations on the same PeerConnection, which
    /// would cause "set remote description called in wrong state" errors.
    /// Multiple on_track callbacks can fire concurrently when a publisher adds
    /// several tracks at once.
    renegotiation_lock: Arc<TokioMutex<()>>,
    /// Migration state for this session (SFU-23 Fix 3).
    /// Tracks whether this session was created via migration and whether migration
    /// has completed. Used by the migration timeout task to avoid removing
    /// successfully-migrated sessions.
    migration_state: Arc<parking_lot::Mutex<Option<PeerMigrationState>>>,
    /// Connection ID for logging
    conn_id: String,
    /// Room ID for cleanup
    room_id: String,
    /// Peer ID for cleanup
    peer_id: String,
}

/// Trait for registering SFU session affinity in a shared store (e.g., Redis).
///
/// In a multi-replica deployment, WebRTC PeerConnections are inherently local
/// to the process that created them. This trait allows the SFU session manager
/// to advertise which replica owns a given session, enabling sticky routing at
/// the load balancer or API gateway layer.
///
/// ## Usage
///
/// - `register`: Called when a new SFU session is created. Stores
///   `conn_id -> replica_id` mapping with a TTL.
/// - `lookup`: Called by the API layer to determine which replica should handle
///   signaling for a given connection.
/// - `unregister`: Called when a session is removed.
///
/// The default implementation (`NoopSessionRegistry`) does nothing, which is
/// correct for single-replica deployments.
#[async_trait::async_trait]
pub trait SessionAffinityRegistry: Send + Sync {
    /// Register session affinity: maps `conn_id` to `replica_id` with a TTL.
    async fn register(&self, conn_id: &str, replica_id: &str, ttl_secs: u64) -> Result<()>;

    /// Look up which replica owns a session. Returns `None` if not found or expired.
    async fn lookup(&self, conn_id: &str) -> Result<Option<String>>;

    /// Remove session affinity mapping.
    async fn unregister(&self, conn_id: &str) -> Result<()>;

    /// Refresh the TTL for an existing session (called periodically by the cleanup task).
    async fn refresh(&self, conn_id: &str, replica_id: &str, ttl_secs: u64) -> Result<()> {
        // Default: re-register (idempotent)
        self.register(conn_id, replica_id, ttl_secs).await
    }
}

/// No-op session registry for single-replica deployments.
pub struct NoopSessionRegistry;

#[async_trait::async_trait]
impl SessionAffinityRegistry for NoopSessionRegistry {
    async fn register(&self, _conn_id: &str, _replica_id: &str, _ttl_secs: u64) -> Result<()> {
        Ok(())
    }
    async fn lookup(&self, _conn_id: &str) -> Result<Option<String>> {
        Ok(None)
    }
    async fn unregister(&self, _conn_id: &str) -> Result<()> {
        Ok(())
    }
}

/// SFU Session Manager - manages server-side PeerConnections for rooms in SFU mode
pub struct SfuSessionManager {
    /// SFU manager for room/peer management
    sfu_manager: Arc<SfuManager>,

    /// ICE server manager
    ice_manager: Arc<IceManager>,

    /// Active sessions: connection_id -> SfuSession (Arc-wrapped for sharing with callbacks)
    sessions: Arc<DashMap<String, SfuSession>>,

    /// Cleanup task cancellation token
    cleanup_cancel_token: CancellationToken,

    /// Session idle timeout (connections with no RTCP stats for this duration are closed)
    session_idle_timeout: Duration,

    /// Unique identifier for this replica/instance (SFU-23 Fix 1).
    /// Used to register session affinity so the load balancer can route
    /// subsequent signaling requests to the correct replica.
    replica_id: String,

    /// Session affinity registry for multi-replica sticky routing (SFU-23 Fix 1).
    /// In single-replica mode, this is a `NoopSessionRegistry`.
    affinity_registry: Arc<dyn SessionAffinityRegistry>,

    /// TTL for session affinity entries (default: 5 minutes, refreshed periodically)
    affinity_ttl_secs: u64,
}

impl SfuSessionManager {
    /// Create a new SFU session manager with default 5-minute idle timeout.
    ///
    /// Uses a no-op session affinity registry (correct for single-replica deployments).
    pub fn new(sfu_manager: Arc<SfuManager>, ice_manager: Arc<IceManager>) -> Arc<Self> {
        Self::with_timeout(sfu_manager, ice_manager, Duration::from_secs(300))
    }

    /// Create a new SFU session manager with custom idle timeout.
    ///
    /// Uses a no-op session affinity registry (correct for single-replica deployments).
    pub fn with_timeout(
        sfu_manager: Arc<SfuManager>,
        ice_manager: Arc<IceManager>,
        session_idle_timeout: Duration,
    ) -> Arc<Self> {
        Self::with_affinity(
            sfu_manager,
            ice_manager,
            session_idle_timeout,
            format!("sfu-{:x}", std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis()),
            Arc::new(NoopSessionRegistry),
        )
    }

    /// Create a new SFU session manager with session affinity support (SFU-23 Fix 1).
    ///
    /// For multi-replica deployments, pass a `SessionAffinityRegistry` implementation
    /// (e.g., backed by Redis) and a unique `replica_id` for this instance.
    /// The load balancer can then query the registry to route signaling
    /// requests to the correct replica.
    pub fn with_affinity(
        sfu_manager: Arc<SfuManager>,
        ice_manager: Arc<IceManager>,
        session_idle_timeout: Duration,
        replica_id: String,
        affinity_registry: Arc<dyn SessionAffinityRegistry>,
    ) -> Arc<Self> {
        let affinity_ttl_secs = session_idle_timeout.as_secs().max(300); // at least 5 min

        let manager = Arc::new(Self {
            sfu_manager,
            ice_manager,
            sessions: Arc::new(DashMap::new()),
            cleanup_cancel_token: CancellationToken::new(),
            session_idle_timeout,
            replica_id,
            affinity_registry,
            affinity_ttl_secs,
        });

        // Start background cleanup task
        Self::start_cleanup_task(Arc::clone(&manager));

        manager
    }

    /// Get this replica's unique identifier.
    pub fn replica_id(&self) -> &str {
        &self.replica_id
    }

    /// Look up which replica owns a session.
    ///
    /// Returns `Some(replica_id)` if the session exists in the affinity registry,
    /// or `None` if not found. If the session is local, callers should handle it
    /// directly; otherwise, the request should be proxied to the owning replica.
    pub async fn lookup_session_replica(&self, conn_id: &str) -> Result<Option<String>> {
        // Fast path: session is local
        if self.sessions.contains_key(conn_id) {
            return Ok(Some(self.replica_id.clone()));
        }
        // Check the shared affinity registry
        self.affinity_registry.lookup(conn_id).await
    }

    /// Start background task to clean up idle sessions.
    ///
    /// Uses a `Weak` reference to `Self` to avoid an Arc cycle between the
    /// `SfuSessionManager` and the spawned cleanup task. The task exits
    /// gracefully when the manager is dropped (Weak::upgrade returns None).
    fn start_cleanup_task(manager: Arc<Self>) {
        let cancel_token = manager.cleanup_cancel_token.clone();
        let weak_manager = Arc::downgrade(&manager);
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(Duration::from_secs(60));
            loop {
                tokio::select! {
                    () = cancel_token.cancelled() => {
                        info!("SFU session cleanup task cancelled");
                        break;
                    }
                    _ = interval.tick() => {
                        let Some(manager) = weak_manager.upgrade() else {
                            info!("SFU session manager dropped, cleanup task exiting");
                            break;
                        };
                        manager.cleanup_idle_sessions().await;
                    }
                }
            }
        });
    }

    /// Clean up idle sessions that have exceeded the timeout, and refresh
    /// session affinity TTLs for active sessions (SFU-23 Fix 1).
    async fn cleanup_idle_sessions(&self) {
        let now = Instant::now();
        let mut expired_sessions = Vec::new();
        let mut active_conn_ids = Vec::new();

        // Identify expired sessions and collect active ones for TTL refresh
        for entry in self.sessions.iter() {
            let (conn_id, session) = (entry.key(), entry.value());
            let last_activity = *session.last_activity.lock();
            let idle_duration = now.duration_since(last_activity);

            if idle_duration > self.session_idle_timeout {
                warn!(
                    conn_id = %conn_id,
                    idle_duration_secs = idle_duration.as_secs(),
                    timeout_secs = self.session_idle_timeout.as_secs(),
                    "SFU session idle timeout, marking for cleanup"
                );
                expired_sessions.push((
                    conn_id.clone(),
                    session.room_id.clone(),
                    session.peer_id.clone(),
                ));
            } else {
                active_conn_ids.push(conn_id.clone());
            }
        }

        // Remove expired sessions
        for (conn_id, room_id, peer_id) in expired_sessions {
            if let Err(e) = self.remove_session(&conn_id, &room_id, &peer_id).await {
                error!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to clean up idle SFU session"
                );
            }
        }

        // Refresh TTLs for active sessions (SFU-23 Fix 1)
        for conn_id in active_conn_ids {
            if let Err(e) = self
                .affinity_registry
                .refresh(&conn_id, &self.replica_id, self.affinity_ttl_secs)
                .await
            {
                debug!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to refresh session affinity TTL"
                );
            }
        }
    }

    /// Check whether a room should use SFU mode based on the current RTC peer count
    pub fn should_use_sfu(&self, rtc_peer_count: usize) -> bool {
        rtc_peer_count >= self.sfu_manager.config().sfu_threshold
    }

    /// Get the SFU threshold from config
    pub fn sfu_threshold(&self) -> usize {
        self.sfu_manager.config().sfu_threshold
    }

    /// Common session setup: creates PeerConnection, registers callbacks, subscribes
    /// to existing tracks, starts RTCP handler, stores the session, and starts
    /// subscriber output.
    ///
    /// Returns `(pc, event_rx, outbound_count)` for caller-specific post-processing.
    async fn setup_session_core(
        &self,
        room_id: &str,
        peer_id: &str,
        conn_id: &str,
        log_prefix: &str,
    ) -> Result<(Arc<PeerConnection>, mpsc::UnboundedReceiver<SfuSignalingEvent>, usize)> {
        let sfu_room_id = RoomId::from(room_id);
        let sfu_peer_id = PeerId::from(peer_id);

        // Get or create the SFU room
        let room = self
            .sfu_manager
            .get_or_create_room(sfu_room_id.clone())
            .await?;

        // Register the peer with the room
        let sfu_peer = room
            .add_peer(sfu_peer_id.clone(), self.sfu_manager.config().max_peers_per_room)
            .await?;

        // Get ICE servers
        let ice_servers = self.ice_manager.get_servers().await;

        // Create server-side PeerConnection
        let pc = PeerConnection::new(
            sfu_peer_id.clone(),
            sfu_room_id.clone(),
            ice_servers,
        )
        .await?;
        let pc = Arc::new(pc);

        // Create signaling event channel
        let (event_tx, event_rx) = mpsc::unbounded_channel();

        // Set up on_track callback
        let room_for_track = Arc::clone(&room);
        let peer_id_for_track = sfu_peer_id.clone();
        let room_id_for_track = sfu_room_id.clone();
        let sessions_for_track = Arc::clone(&self.sessions);
        let log_prefix_track = log_prefix.to_string();
        let simulcast_enabled = self.sfu_manager.config().enable_simulcast;

        pc.pc.on_track(Box::new(
            move |remote_track: Arc<webrtc::track::track_remote::TrackRemote>,
                  rtp_receiver: Arc<webrtc::rtp_transceiver::rtp_receiver::RTCRtpReceiver>,
                  _transceiver: Arc<webrtc::rtp_transceiver::RTCRtpTransceiver>| {
                let room = Arc::clone(&room_for_track);
                let peer_id = peer_id_for_track.clone();
                let room_id = room_id_for_track.clone();
                let sessions = sessions_for_track.clone();
                let prefix = log_prefix_track.clone();
                Box::pin(async move {
                    let track_id = TrackId::from(remote_track.id());
                    let kind = TrackKind::from(remote_track.kind());
                    let codec = remote_track.codec().capability.mime_type.clone();

                    info!(
                        peer_id = %peer_id,
                        room_id = %room_id,
                        track_id = %track_id,
                        kind = ?kind,
                        codec = %codec,
                        "{}: Received track from peer", prefix
                    );

                    let media_track = Arc::new(MediaTrack::new(
                        track_id.clone(),
                        peer_id.clone(),
                        remote_track,
                        rtp_receiver,
                    ));

                    // Set initial simulcast quality layer for video tracks only
                    // when simulcast is enabled in config
                    if simulcast_enabled && kind == TrackKind::Video {
                        media_track.set_quality_layer(crate::track::QualityLayer::Medium);
                    }

                    if let Err(e) = room
                        .add_published_track(&peer_id, track_id.clone(), media_track)
                        .await
                    {
                        error!(
                            peer_id = %peer_id,
                            track_id = %track_id,
                            error = %e,
                            "{}: Failed to register track with room", prefix
                        );
                        return;
                    }

                    // SFU-23 Fix 4: Collect subscriber sessions into a Vec FIRST,
                    // then drop the DashMap iterator. This prevents:
                    // 1. Missing newly-joined peers (iterator snapshot is stale but safe)
                    // 2. Holding the DashMap shard locks during async renegotiation
                    let subscribers: Vec<(
                        Arc<PeerConnection>,
                        String,  // peer_id
                        mpsc::UnboundedSender<SfuSignalingEvent>,
                        Arc<TokioMutex<()>>,  // renegotiation lock
                    )> = sessions
                        .iter()
                        .filter(|entry| entry.value().peer_id != peer_id.as_str())
                        .map(|entry| {
                            let s = entry.value();
                            (
                                Arc::clone(&s.pc),
                                s.peer_id.clone(),
                                s.event_tx.clone(),
                                Arc::clone(&s.renegotiation_lock),
                            )
                        })
                        .collect();
                    // DashMap iterator is now dropped, shard locks released.

                    for (sub_pc, sub_peer_id, sub_event_tx, reneg_lock) in subscribers {
                        if let Err(e) = sub_pc
                            .add_outbound_track(track_id.clone(), kind, &codec)
                            .await
                        {
                            warn!(
                                subscriber_peer = %sub_peer_id,
                                track_id = %track_id,
                                error = %e,
                                "{}: Failed to add outbound track to subscriber", prefix
                            );
                        } else {
                            let subscriber_peer_id = PeerId::from(sub_peer_id.as_str());
                            if let Err(e) = room
                                .subscribe_track(&subscriber_peer_id, &track_id)
                                .await
                            {
                                warn!(
                                    subscriber_peer = %sub_peer_id,
                                    track_id = %track_id,
                                    error = %e,
                                    "{}: Failed to subscribe peer to track", prefix
                                );
                            }

                            // SFU-12: Trigger SDP renegotiation so the subscriber
                            // learns about the newly added track. Without this, the
                            // remote peer's SDP never includes the new m= line and
                            // the track is effectively invisible.
                            //
                            // SFU-23 Fix 4: Acquire per-peer renegotiation lock to
                            // serialize concurrent offer creation. Without this,
                            // multiple on_track callbacks racing on the same peer
                            // would produce invalid SDP states.
                            let _reneg_guard = reneg_lock.lock().await;
                            match sub_pc.create_offer().await {
                                Ok(offer) => {
                                    let offer_json = match serde_json::to_string(&offer) {
                                        Ok(json) => json,
                                        Err(e) => {
                                            warn!(
                                                subscriber_peer = %sub_peer_id,
                                                error = %e,
                                                "{}: Failed to serialize renegotiation offer", prefix
                                            );
                                            continue;
                                        }
                                    };
                                    if sub_event_tx.send(SfuSignalingEvent::SdpOffer {
                                        peer_id: sub_peer_id.clone(),
                                        sdp: offer_json,
                                    }).is_err() {
                                        debug!(
                                            subscriber_peer = %sub_peer_id,
                                            "{}: Signaling channel closed for renegotiation", prefix
                                        );
                                    } else {
                                        info!(
                                            subscriber_peer = %sub_peer_id,
                                            track_id = %track_id,
                                            "{}: Triggered SDP renegotiation after new track", prefix
                                        );
                                    }
                                }
                                Err(e) => {
                                    warn!(
                                        subscriber_peer = %sub_peer_id,
                                        error = %e,
                                        "{}: Failed to create renegotiation offer", prefix
                                    );
                                }
                            }
                        }
                    }
                })
            },
        ));

        // Set up on_ice_candidate callback with security filtering
        let event_tx_for_ice = event_tx.clone();
        let peer_id_str = peer_id.to_string();
        let log_prefix_ice = log_prefix.to_string();

        pc.pc.on_ice_candidate(Box::new(move |candidate: Option<RTCIceCandidate>| {
            let event_tx = event_tx_for_ice.clone();
            let peer_id = peer_id_str.clone();
            let prefix = log_prefix_ice.clone();
            Box::pin(async move {
                if let Some(candidate) = candidate {
                    if let Some(filtered) = filter_ice_candidate(&candidate) {
                        let candidate_json = match filtered.to_json() {
                            Ok(init) => match serde_json::to_string(&init) {
                                Ok(json) => json,
                                Err(e) => {
                                    warn!(error = %e, "Failed to serialize ICE candidate");
                                    return;
                                }
                            },
                            Err(e) => {
                                warn!(error = %e, "Failed to convert ICE candidate to JSON");
                                return;
                            }
                        };

                        debug!(
                            peer_id = %peer_id,
                            candidate_type = %filtered.typ,
                            "{}: Sending filtered ICE candidate to signaling channel", prefix
                        );

                        if event_tx
                            .send(SfuSignalingEvent::IceCandidate {
                                peer_id: peer_id.clone(),
                                candidate_json,
                            })
                            .is_err()
                        {
                            debug!(peer_id = %peer_id, "{}: Signaling event channel closed", prefix);
                        }
                    } else {
                        debug!(
                            peer_id = %peer_id,
                            candidate_type = %candidate.typ,
                            "ICE candidate filtered (security)"
                        );
                        return;
                    }
                }
            })
        }));

        // Set up connection state monitoring.
        // Pass event_tx so ICE restart offers can be delivered to the client (SFU-23 Fix 2).
        let network_monitor = room.network_monitor().clone();
        pc.setup_callbacks(network_monitor.clone(), Some(event_tx.clone())).await?;

        // Add outbound tracks for all existing published tracks from other peers
        let existing_tracks = room.get_published_track_info();
        let mut outbound_count: usize = 0;
        for (track_id, publisher_peer_id, kind, codec) in existing_tracks.iter() {
            if *publisher_peer_id == sfu_peer_id {
                continue;
            }
            let tid: TrackId = track_id.clone();
            if let Err(e) = pc.add_outbound_track(tid, *kind, codec.as_str()).await {
                warn!(
                    peer_id = %sfu_peer_id,
                    track_id = %track_id,
                    error = %e,
                    "{}: Failed to add outbound track for existing published track", log_prefix
                );
            } else {
                outbound_count += 1;
                if let Err(e) = room.subscribe_track(&sfu_peer_id, track_id).await {
                    warn!(
                        peer_id = %sfu_peer_id,
                        track_id = %track_id,
                        error = %e,
                        "{}: Failed to subscribe to existing track", log_prefix
                    );
                }
            }
        }

        // Start RTCP handler for bandwidth estimation and network quality monitoring,
        // but only if bandwidth estimation is enabled in config.
        let (rtcp_handler, rtcp_task) = if self.sfu_manager.config().enable_bandwidth_estimation {
            let handler = RtcpHandler::new(
                sfu_peer_id.clone(),
                network_monitor,
                Arc::clone(&sfu_peer),
            );
            let task = match handler.start(Arc::clone(&pc.pc), vec![]).await {
                Ok(handle) => Some(handle),
                Err(e) => {
                    warn!(
                        peer_id = %sfu_peer_id,
                        error = %e,
                        "{}: Failed to start RTCP handler, continuing without bandwidth estimation", log_prefix
                    );
                    None
                }
            };
            (Some(handler), task)
        } else {
            debug!(
                peer_id = %sfu_peer_id,
                "{}: Bandwidth estimation disabled by config, skipping RTCP handler", log_prefix
            );
            (None, None)
        };

        // Store session (event_tx is cloned so the on_track callback can trigger
        // renegotiation on subscriber sessions)
        self.sessions.insert(
            conn_id.to_string(),
            SfuSession {
                pc: Arc::clone(&pc),
                room: Arc::clone(&room),
                sfu_peer: Arc::clone(&sfu_peer),
                rtcp_task,
                rtcp_handler,
                event_tx: event_tx.clone(),
                last_activity: Arc::new(parking_lot::Mutex::new(Instant::now())),
                renegotiation_lock: Arc::new(TokioMutex::new(())),
                migration_state: Arc::new(parking_lot::Mutex::new(None)),
                conn_id: conn_id.to_string(),
                room_id: room_id.to_string(),
                peer_id: peer_id.to_string(),
            },
        );

        // Register session affinity so load balancers can route signaling
        // requests to this replica (SFU-23 Fix 1).
        if let Err(e) = self
            .affinity_registry
            .register(conn_id, &self.replica_id, self.affinity_ttl_secs)
            .await
        {
            warn!(
                conn_id = %conn_id,
                replica_id = %self.replica_id,
                error = %e,
                "{}: Failed to register session affinity (non-fatal)", log_prefix
            );
        }

        // Start subscriber output for this peer
        pc.start_subscriber_output(sfu_peer).await?;

        // Spawn ICE connection timeout task: if ICE doesn't reach Connected
        // within the configured timeout, close the peer connection and remove
        // the session to prevent ghost connections consuming resources.
        let ice_timeout_secs = self.sfu_manager.config().ice_connection_timeout_secs;
        if ice_timeout_secs > 0 {
            let pc_weak = Arc::downgrade(&pc);
            let sessions_ref = Arc::clone(&self.sessions);
            let conn_id_owned = conn_id.to_string();
            let room_id_owned = room_id.to_string();
            let peer_id_owned = peer_id.to_string();
            tokio::spawn(async move {
                tokio::time::sleep(Duration::from_secs(ice_timeout_secs)).await;
                let Some(pc) = pc_weak.upgrade() else { return };
                let state = pc.pc.ice_connection_state();
                if state != webrtc::ice_transport::ice_connection_state::RTCIceConnectionState::Connected
                    && state != webrtc::ice_transport::ice_connection_state::RTCIceConnectionState::Completed
                {
                    warn!(
                        conn_id = %conn_id_owned,
                        peer_id = %peer_id_owned,
                        ice_state = ?state,
                        timeout_secs = ice_timeout_secs,
                        "ICE connection timeout reached, closing peer connection"
                    );
                    let _ = pc.pc.close().await;
                    sessions_ref.remove(&conn_id_owned);
                    info!(
                        conn_id = %conn_id_owned,
                        peer_id = %peer_id_owned,
                        room_id = %room_id_owned,
                        "Removed SFU session after ICE timeout"
                    );
                }
            });
        }

        Ok((pc, event_rx, outbound_count))
    }

    /// Create an SFU session for a peer.
    ///
    /// This creates a server-side `PeerConnection`, registers the peer with the
    /// SFU room, and sets up track/ICE callbacks.
    ///
    /// Returns an `UnboundedReceiver` for signaling events (ICE candidates, etc.)
    /// that must be forwarded to the client.
    pub async fn create_session(
        &self,
        room_id: &str,
        peer_id: &str,
        conn_id: &str,
    ) -> Result<mpsc::UnboundedReceiver<SfuSignalingEvent>> {
        let (_pc, event_rx, outbound_count) =
            self.setup_session_core(room_id, peer_id, conn_id, "SFU").await?;

        info!(
            room_id = %room_id,
            peer_id = %peer_id,
            conn_id = %conn_id,
            outbound_track_count = outbound_count,
            "SFU session created"
        );

        Ok(event_rx)
    }

    /// Handle an SDP offer from the client, returning the server's SDP answer
    pub async fn handle_offer(
        &self,
        conn_id: &str,
        sdp_json: &str,
    ) -> Result<String> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        // Parse the SDP offer
        let offer: RTCSessionDescription = serde_json::from_str(sdp_json)
            .map_err(|e| anyhow!("Invalid SDP offer JSON: {}", e))?;

        // Generate answer
        let answer = session.pc.handle_offer(offer).await?;

        // Serialize answer
        let answer_json = serde_json::to_string(&answer)
            .map_err(|e| anyhow!("Failed to serialize SDP answer: {}", e))?;

        // Update activity timestamp
        drop(session);
        self.touch_session(conn_id);

        Ok(answer_json)
    }

    /// Handle an ICE candidate from the client
    pub async fn add_ice_candidate(
        &self,
        conn_id: &str,
        candidate_json: &str,
    ) -> Result<()> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        let candidate_init: webrtc::ice_transport::ice_candidate::RTCIceCandidateInit =
            serde_json::from_str(candidate_json)
                .map_err(|e| anyhow!("Invalid ICE candidate JSON: {}", e))?;

        session.pc.add_ice_candidate(candidate_init).await?;

        // Update activity timestamp
        drop(session);
        self.touch_session(conn_id);

        Ok(())
    }

    /// Update activity timestamp for a session (prevents idle timeout)
    fn touch_session(&self, conn_id: &str) {
        if let Some(session) = self.sessions.get(conn_id) {
            *session.last_activity.lock() = Instant::now();
        }
    }

    /// Check if a connection has an active SFU session
    pub fn has_session(&self, conn_id: &str) -> bool {
        self.sessions.contains_key(conn_id)
    }

    /// Remove an SFU session and clean up resources
    pub async fn remove_session(
        &self,
        conn_id: &str,
        room_id: &str,
        peer_id: &str,
    ) -> Result<()> {
        if let Some((_, session)) = self.sessions.remove(conn_id) {
            // Close the PeerConnection
            if let Err(e) = session.pc.close().await {
                warn!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to close SFU PeerConnection"
                );
            }

            // Remove the peer from the SFU room
            let sfu_room_id = RoomId::from(room_id);
            let sfu_peer_id = PeerId::from(peer_id);
            if let Err(e) = self
                .sfu_manager
                .remove_peer_from_room(&sfu_room_id, &sfu_peer_id)
                .await
            {
                warn!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to remove peer from SFU room"
                );
            }

            // Unregister session affinity (SFU-23 Fix 1)
            if let Err(e) = self.affinity_registry.unregister(conn_id).await {
                warn!(
                    conn_id = %conn_id,
                    error = %e,
                    "Failed to unregister session affinity (non-fatal)"
                );
            }

            info!(
                room_id = %room_id,
                peer_id = %peer_id,
                conn_id = %conn_id,
                "SFU session removed"
            );
        }

        Ok(())
    }

    /// Get the number of active SFU sessions
    pub fn session_count(&self) -> usize {
        self.sessions.len()
    }

    /// Complete migration for a room, transitioning it from Migrating to SFU mode.
    ///
    /// Called by the API layer after all existing P2P peers have been sent migration
    /// offers (or failed). This finalizes the room state so new peers join in SFU mode.
    pub async fn complete_room_migration(&self, room_id: &str) -> Result<()> {
        let sfu_room_id = RoomId::from(room_id);
        let room = self
            .sfu_manager
            .get_or_create_room(sfu_room_id)
            .await?;
        room.complete_migration().await
    }

    /// Create an SFU session for an existing P2P peer during migration.
    ///
    /// Unlike `create_session`, this creates a server-side `PeerConnection` and
    /// generates an SDP offer (rather than waiting for the client to send one).
    /// The client will respond with an SDP answer via `SfuMigrationAnswer`.
    ///
    /// Returns the SDP offer and a signaling event receiver, or an error if
    /// session creation fails.
    pub async fn create_migration_session(
        &self,
        room_id: &str,
        peer_id: &str,
        conn_id: &str,
    ) -> Result<PeerMigrationResult> {
        let (pc, event_rx, outbound_count) =
            self.setup_session_core(room_id, peer_id, conn_id, "SFU migration").await?;

        // SFU-23 Fix 3: Mark session as Migrating so timeout cleanup can
        // distinguish incomplete migrations from successfully completed ones.
        self.set_migration_state(conn_id, PeerMigrationState::Migrating);

        // Create SDP offer from the server side (after adding outbound tracks
        // so they are included in the SDP offer)
        let offer = pc.create_offer().await?;
        let offer_json = serde_json::to_string(&offer)
            .map_err(|e| anyhow!("Failed to serialize SDP offer: {}", e))?;

        info!(
            room_id = %room_id,
            peer_id = %peer_id,
            conn_id = %conn_id,
            outbound_track_count = outbound_count,
            "SFU migration session created, offer generated"
        );

        Ok(PeerMigrationResult {
            conn_id: conn_id.to_string(),
            sdp_offer: offer_json,
            event_rx,
        })
    }

    /// Handle an SDP answer from a migrating peer
    pub async fn handle_migration_answer(
        &self,
        conn_id: &str,
        sdp_json: &str,
    ) -> Result<()> {
        let session = self
            .sessions
            .get(conn_id)
            .ok_or_else(|| anyhow!("No SFU session for connection: {}", conn_id))?;

        // Parse the SDP answer
        let answer: RTCSessionDescription = serde_json::from_str(sdp_json)
            .map_err(|e| anyhow!("Invalid SDP answer JSON: {}", e))?;

        // Set remote description (completes the signaling handshake)
        session.pc.handle_answer(answer).await?;

        info!(
            conn_id = %conn_id,
            "SFU migration: answer processed, ICE negotiation in progress"
        );

        // SFU-23 Fix 3: Mark migration as Completed so the timeout task
        // won't remove this successfully-migrated session.
        *session.migration_state.lock() = Some(PeerMigrationState::Completed);

        // Update activity timestamp
        drop(session);
        self.touch_session(conn_id);

        Ok(())
    }

    /// Set the migration state for a session (SFU-23 Fix 3).
    fn set_migration_state(&self, conn_id: &str, state: PeerMigrationState) {
        if let Some(session) = self.sessions.get(conn_id) {
            *session.migration_state.lock() = Some(state);
        }
    }

    /// Get the migration state for a session (SFU-23 Fix 3).
    ///
    /// Returns `None` if the session was not created via migration (i.e., it was
    /// created via `create_session` for a peer joining after SFU mode was active).
    pub fn get_migration_state(&self, conn_id: &str) -> Option<PeerMigrationState> {
        self.sessions
            .get(conn_id)
            .and_then(|session| *session.migration_state.lock())
    }
}

impl Drop for SfuSessionManager {
    fn drop(&mut self) {
        // Cancel cleanup task on drop
        self.cleanup_cancel_token.cancel();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::SfuConfig;

    #[tokio::test]
    async fn test_should_use_sfu() {
        let config = SfuConfig {
            sfu_threshold: 3,
            ..SfuConfig::default()
        };
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::with_timeout(
            manager,
            ice_manager,
            Duration::from_secs(300),
        );

        assert!(!session_mgr.should_use_sfu(0));
        assert!(!session_mgr.should_use_sfu(1));
        assert!(!session_mgr.should_use_sfu(2));
        assert!(session_mgr.should_use_sfu(3));
        assert!(session_mgr.should_use_sfu(10));
    }

    #[tokio::test]
    async fn test_sfu_threshold() {
        let config = SfuConfig {
            sfu_threshold: 5,
            ..SfuConfig::default()
        };
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::with_timeout(
            manager,
            ice_manager,
            Duration::from_secs(300),
        );

        assert_eq!(session_mgr.sfu_threshold(), 5);
    }

    #[tokio::test]
    async fn test_has_session_empty() {
        let config = SfuConfig::default();
        let manager = SfuManager::new(config);
        let ice_manager = Arc::new(IceManager::new());
        let session_mgr = SfuSessionManager::with_timeout(
            manager,
            ice_manager,
            Duration::from_secs(300),
        );

        assert!(!session_mgr.has_session("non-existent"));
        assert_eq!(session_mgr.session_count(), 0);
    }

    #[test]
    fn test_is_private_ip_v4() {
        use std::net::Ipv4Addr;

        // Private networks
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1))));
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(172, 16, 0, 1))));
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(192, 168, 1, 1))));

        // Loopback
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1))));

        // Link-local
        assert!(super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(169, 254, 0, 1))));

        // Public IPs
        assert!(!super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(8, 8, 8, 8))));
        assert!(!super::is_private_ip(&IpAddr::V4(Ipv4Addr::new(1, 1, 1, 1))));
    }

    #[test]
    fn test_is_private_ip_v6() {
        use std::net::Ipv6Addr;

        // Loopback
        assert!(super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1))));

        // Link-local
        assert!(super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0xfe80, 0, 0, 0, 0, 0, 0, 1))));

        // Unique local
        assert!(super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0xfc00, 0, 0, 0, 0, 0, 0, 1))));

        // Public
        assert!(!super::is_private_ip(&IpAddr::V6(Ipv6Addr::new(0x2001, 0x4860, 0x4860, 0, 0, 0, 0, 0x8888))));
    }

    #[test]
    fn test_filter_ice_candidate_reflexive() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Reflexive candidates should always pass
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Srflx;
        candidate.address = "203.0.113.1".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_some());
    }

    #[test]
    fn test_filter_ice_candidate_relay() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Relay candidates should always pass
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Relay;
        candidate.address = "203.0.113.1".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_some());
    }

    #[test]
    fn test_filter_ice_candidate_private_host() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Private host candidates should be filtered
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Host;
        candidate.address = "192.168.1.1".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_none());
    }

    #[test]
    fn test_filter_ice_candidate_public_host() {
        use webrtc::ice_transport::ice_candidate_type::RTCIceCandidateType;

        // Public host candidates should pass
        let mut candidate = RTCIceCandidate::default();
        candidate.typ = RTCIceCandidateType::Host;
        candidate.address = "8.8.8.8".to_string();

        assert!(super::filter_ice_candidate(&candidate).is_some());
    }
}
