// This file is @generated by prost-build.
/// Login request
/// SECURITY: Prefer hashed_password over password when possible to reduce plaintext exposure.
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_LoginRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// SECURITY: Plaintext credential - requires TLS in transit. Prefer hashed_password.
    #[prost(string, tag = "3")]
    #[serde(default)]
    pub password: ::prost::alloc::string::String,
    /// Hashed password (if provided, password is ignored)
    #[prost(string, tag = "4")]
    #[serde(default)]
    pub hashed_password: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "5")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Login response
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_LoginResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    /// SHA-256(host) identifier for stored credential
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
}
/// List directory request
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_ListRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    /// Stored credential identifier
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[serde(default)]
    pub path: ::prost::alloc::string::String,
    /// Directory password (optional)
    #[prost(string, tag = "3")]
    #[serde(default)]
    pub password: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    #[serde(default)]
    pub page: u64,
    #[prost(uint64, tag = "5")]
    #[serde(default)]
    pub per_page: u64,
    #[prost(bool, tag = "6")]
    #[serde(default)]
    pub refresh: bool,
    /// Optional provider instance name
    #[prost(string, tag = "7")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// List directory response
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_ListResponse))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag = "1")]
    pub content: ::prost::alloc::vec::Vec<FileItem>,
    #[prost(uint64, tag = "2")]
    pub total: u64,
}
/// File/directory item
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_FileItem))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileItem {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size: u64,
    #[prost(bool, tag = "3")]
    pub is_dir: bool,
    #[prost(uint64, tag = "4")]
    pub modified: u64,
    #[prost(string, tag = "5")]
    pub sign: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub thumb: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub r#type: u64,
}
/// Get user info request
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_GetMeRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeRequest {
    /// Stored credential identifier
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get user info response
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_GetMeResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeResponse {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub base_path: ::prost::alloc::string::String,
}
/// Logout request
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_LogoutRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
    /// Which credential to unbind
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Logout response
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_LogoutResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Get binds request
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_GetBindsRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBindsRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get binds response
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_GetBindsResponse))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBindsResponse {
    #[prost(message, repeated, tag = "1")]
    pub binds: ::prost::alloc::vec::Vec<BindInfo>,
}
/// Saved credential information
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_alist_BindInfo))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    /// Unix epoch timestamp
    #[prost(int64, tag = "4")]
    pub created_at: i64,
}
/// Generated client implementations.
pub mod alist_provider_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Alist Provider Service
    ///
    /// Client-facing API for Alist network storage access
    #[derive(Debug, Clone)]
    pub struct AlistProviderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AlistProviderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AlistProviderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AlistProviderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AlistProviderServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Login to Alist server (persist credential)
        pub async fn login(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginRequest>,
        ) -> std::result::Result<tonic::Response<super::LoginResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.alist.AlistProviderService/Login",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.alist.AlistProviderService",
                        "Login",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List directory contents (uses stored credential via server_id)
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.alist.AlistProviderService/List",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("synctv.provider.alist.AlistProviderService", "List"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get current user info (uses stored credential via server_id)
        pub async fn get_me(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMeRequest>,
        ) -> std::result::Result<tonic::Response<super::GetMeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.alist.AlistProviderService/GetMe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.alist.AlistProviderService",
                        "GetMe",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Logout from Alist (delete stored credential)
        pub async fn logout(
            &mut self,
            request: impl tonic::IntoRequest<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.alist.AlistProviderService/Logout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.alist.AlistProviderService",
                        "Logout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get saved credentials (binds)
        pub async fn get_binds(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBindsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBindsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.alist.AlistProviderService/GetBinds",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.alist.AlistProviderService",
                        "GetBinds",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod alist_provider_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AlistProviderServiceServer.
    #[async_trait]
    pub trait AlistProviderService: std::marker::Send + std::marker::Sync + 'static {
        /// Login to Alist server (persist credential)
        async fn login(
            &self,
            request: tonic::Request<super::LoginRequest>,
        ) -> std::result::Result<tonic::Response<super::LoginResponse>, tonic::Status>;
        /// List directory contents (uses stored credential via server_id)
        async fn list(
            &self,
            request: tonic::Request<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListResponse>, tonic::Status>;
        /// Get current user info (uses stored credential via server_id)
        async fn get_me(
            &self,
            request: tonic::Request<super::GetMeRequest>,
        ) -> std::result::Result<tonic::Response<super::GetMeResponse>, tonic::Status>;
        /// Logout from Alist (delete stored credential)
        async fn logout(
            &self,
            request: tonic::Request<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status>;
        /// Get saved credentials (binds)
        async fn get_binds(
            &self,
            request: tonic::Request<super::GetBindsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBindsResponse>,
            tonic::Status,
        >;
    }
    /// Alist Provider Service
    ///
    /// Client-facing API for Alist network storage access
    #[derive(Debug)]
    pub struct AlistProviderServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AlistProviderServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for AlistProviderServiceServer<T>
    where
        T: AlistProviderService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/synctv.provider.alist.AlistProviderService/Login" => {
                    #[allow(non_camel_case_types)]
                    struct LoginSvc<T: AlistProviderService>(pub Arc<T>);
                    impl<
                        T: AlistProviderService,
                    > tonic::server::UnaryService<super::LoginRequest> for LoginSvc<T> {
                        type Response = super::LoginResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AlistProviderService>::login(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.alist.AlistProviderService/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: AlistProviderService>(pub Arc<T>);
                    impl<
                        T: AlistProviderService,
                    > tonic::server::UnaryService<super::ListRequest> for ListSvc<T> {
                        type Response = super::ListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AlistProviderService>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.alist.AlistProviderService/GetMe" => {
                    #[allow(non_camel_case_types)]
                    struct GetMeSvc<T: AlistProviderService>(pub Arc<T>);
                    impl<
                        T: AlistProviderService,
                    > tonic::server::UnaryService<super::GetMeRequest> for GetMeSvc<T> {
                        type Response = super::GetMeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AlistProviderService>::get_me(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.alist.AlistProviderService/Logout" => {
                    #[allow(non_camel_case_types)]
                    struct LogoutSvc<T: AlistProviderService>(pub Arc<T>);
                    impl<
                        T: AlistProviderService,
                    > tonic::server::UnaryService<super::LogoutRequest>
                    for LogoutSvc<T> {
                        type Response = super::LogoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AlistProviderService>::logout(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.alist.AlistProviderService/GetBinds" => {
                    #[allow(non_camel_case_types)]
                    struct GetBindsSvc<T: AlistProviderService>(pub Arc<T>);
                    impl<
                        T: AlistProviderService,
                    > tonic::server::UnaryService<super::GetBindsRequest>
                    for GetBindsSvc<T> {
                        type Response = super::GetBindsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBindsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AlistProviderService>::get_binds(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBindsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AlistProviderServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "synctv.provider.alist.AlistProviderService";
    impl<T> tonic::server::NamedService for AlistProviderServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
