// This file is @generated by prost-build.
/// Parse video URL request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.ParseRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_ParseRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParseRequest {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Parse video URL response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.ParseResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_ParseResponse))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseResponse {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub actors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub videos: ::prost::alloc::vec::Vec<VideoInfo>,
}
/// Video information
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.VideoInfo")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_VideoInfo))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VideoInfo {
    #[prost(string, tag = "1")]
    pub bvid: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub cid: i64,
    #[prost(int64, tag = "3")]
    pub epid: i64,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub cover: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub is_live: bool,
}
/// QR code login request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.LoginQRRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_LoginQRRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginQrRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// QR code response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.QRCodeResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_QRCodeResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QrCodeResponse {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
/// Check QR status request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.CheckQRRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_CheckQRRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckQrRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// QR status response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.QRStatusResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_QRStatusResponse))]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QrStatusResponse {
    #[prost(enumeration = "QrLoginStatus", tag = "1")]
    pub status: i32,
}
/// Get captcha request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.GetCaptchaRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_GetCaptchaRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCaptchaRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Captcha response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.CaptchaResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_CaptchaResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptchaResponse {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub gt: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub challenge: ::prost::alloc::string::String,
}
/// Send SMS request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.SendSMSRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_SendSMSRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendSmsRequest {
    #[prost(string, tag = "1")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub challenge: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub validate: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "5")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Send SMS response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.SendSMSResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_SendSMSResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendSmsResponse {
    #[prost(string, tag = "1")]
    pub captcha_key: ::prost::alloc::string::String,
}
/// Login with SMS request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.LoginSMSRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_LoginSMSRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSmsRequest {
    #[prost(string, tag = "1")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub captcha_key: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "4")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Login with SMS response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.LoginSMSResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_LoginSMSResponse))]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSmsResponse {}
/// User info request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.UserInfoRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_UserInfoRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfoRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// User info response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.UserInfoResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_UserInfoResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfoResponse {
    #[prost(bool, tag = "1")]
    pub is_login: bool,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub face: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_vip: bool,
}
/// Logout request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.LogoutRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_LogoutRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    #[serde(default)]
    pub instance_name: ::prost::alloc::string::String,
}
/// Logout response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.LogoutResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_LogoutResponse))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Get binds request
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.GetBindsRequest")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_GetBindsRequest))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBindsRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get binds response
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.GetBindsResponse")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_GetBindsResponse))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBindsResponse {
    #[prost(message, repeated, tag = "1")]
    pub binds: ::prost::alloc::vec::Vec<BindInfo>,
}
/// Saved credential information
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "synctv.provider.bilibili.BindInfo")]
#[prost_reflect(descriptor_pool = "crate::PROVIDERS_DESCRIPTOR_POOL")]
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_BindInfo))]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
    /// Unix epoch timestamp
    #[prost(int64, tag = "3")]
    pub created_at: i64,
}
/// QR login status enum
/// Values match synctv-media-providers QRCodeStatus for compatibility
#[derive(serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "openapi", allow(clippy::large_stack_arrays))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "openapi", schema(as = synctv_provider_bilibili_QRLoginStatus))]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QrLoginStatus {
    Unspecified = 0,
    Expired = 1,
    NotScanned = 2,
    Scanned = 3,
    Success = 4,
}
impl QrLoginStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "QR_LOGIN_STATUS_UNSPECIFIED",
            Self::Expired => "QR_LOGIN_STATUS_EXPIRED",
            Self::NotScanned => "QR_LOGIN_STATUS_NOT_SCANNED",
            Self::Scanned => "QR_LOGIN_STATUS_SCANNED",
            Self::Success => "QR_LOGIN_STATUS_SUCCESS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "QR_LOGIN_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "QR_LOGIN_STATUS_EXPIRED" => Some(Self::Expired),
            "QR_LOGIN_STATUS_NOT_SCANNED" => Some(Self::NotScanned),
            "QR_LOGIN_STATUS_SCANNED" => Some(Self::Scanned),
            "QR_LOGIN_STATUS_SUCCESS" => Some(Self::Success),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod bilibili_provider_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Bilibili Provider Service
    ///
    /// Client-facing API for Bilibili video parsing, login, and user management
    #[derive(Debug, Clone)]
    pub struct BilibiliProviderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BilibiliProviderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BilibiliProviderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BilibiliProviderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BilibiliProviderServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Parse Bilibili URL (video, anime, live), using the user's global bind when available
        pub async fn parse(
            &mut self,
            request: impl tonic::IntoRequest<super::ParseRequest>,
        ) -> std::result::Result<tonic::Response<super::ParseResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/Parse",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "Parse",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Generate QR code for login
        pub async fn login_qr(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginQrRequest>,
        ) -> std::result::Result<tonic::Response<super::QrCodeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/LoginQR",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "LoginQR",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Check QR code login status (persists credential on success)
        pub async fn check_qr(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckQrRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QrStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/CheckQR",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "CheckQR",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get captcha for SMS login
        pub async fn get_captcha(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCaptchaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptchaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/GetCaptcha",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "GetCaptcha",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Send SMS verification code
        pub async fn send_sms(
            &mut self,
            request: impl tonic::IntoRequest<super::SendSmsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendSmsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/SendSMS",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "SendSMS",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Login with SMS code (persists credential on success)
        pub async fn login_sms(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginSmsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoginSmsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/LoginSMS",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "LoginSMS",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get user info from the user's global bind
        pub async fn get_user_info(
            &mut self,
            request: impl tonic::IntoRequest<super::UserInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/GetUserInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "GetUserInfo",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Logout (delete stored credential)
        pub async fn logout(
            &mut self,
            request: impl tonic::IntoRequest<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/Logout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "Logout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get saved credentials (binds)
        pub async fn get_binds(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBindsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBindsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.provider.bilibili.BilibiliProviderService/GetBinds",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.provider.bilibili.BilibiliProviderService",
                        "GetBinds",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod bilibili_provider_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BilibiliProviderServiceServer.
    #[async_trait]
    pub trait BilibiliProviderService: std::marker::Send + std::marker::Sync + 'static {
        /// Parse Bilibili URL (video, anime, live), using the user's global bind when available
        async fn parse(
            &self,
            request: tonic::Request<super::ParseRequest>,
        ) -> std::result::Result<tonic::Response<super::ParseResponse>, tonic::Status>;
        /// Generate QR code for login
        async fn login_qr(
            &self,
            request: tonic::Request<super::LoginQrRequest>,
        ) -> std::result::Result<tonic::Response<super::QrCodeResponse>, tonic::Status>;
        /// Check QR code login status (persists credential on success)
        async fn check_qr(
            &self,
            request: tonic::Request<super::CheckQrRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QrStatusResponse>,
            tonic::Status,
        >;
        /// Get captcha for SMS login
        async fn get_captcha(
            &self,
            request: tonic::Request<super::GetCaptchaRequest>,
        ) -> std::result::Result<tonic::Response<super::CaptchaResponse>, tonic::Status>;
        /// Send SMS verification code
        async fn send_sms(
            &self,
            request: tonic::Request<super::SendSmsRequest>,
        ) -> std::result::Result<tonic::Response<super::SendSmsResponse>, tonic::Status>;
        /// Login with SMS code (persists credential on success)
        async fn login_sms(
            &self,
            request: tonic::Request<super::LoginSmsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoginSmsResponse>,
            tonic::Status,
        >;
        /// Get user info from the user's global bind
        async fn get_user_info(
            &self,
            request: tonic::Request<super::UserInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserInfoResponse>,
            tonic::Status,
        >;
        /// Logout (delete stored credential)
        async fn logout(
            &self,
            request: tonic::Request<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status>;
        /// Get saved credentials (binds)
        async fn get_binds(
            &self,
            request: tonic::Request<super::GetBindsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBindsResponse>,
            tonic::Status,
        >;
    }
    /// Bilibili Provider Service
    ///
    /// Client-facing API for Bilibili video parsing, login, and user management
    #[derive(Debug)]
    pub struct BilibiliProviderServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BilibiliProviderServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for BilibiliProviderServiceServer<T>
    where
        T: BilibiliProviderService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/synctv.provider.bilibili.BilibiliProviderService/Parse" => {
                    #[allow(non_camel_case_types)]
                    struct ParseSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::ParseRequest> for ParseSvc<T> {
                        type Response = super::ParseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ParseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::parse(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ParseSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/LoginQR" => {
                    #[allow(non_camel_case_types)]
                    struct LoginQRSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::LoginQrRequest>
                    for LoginQRSvc<T> {
                        type Response = super::QrCodeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginQrRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::login_qr(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginQRSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/CheckQR" => {
                    #[allow(non_camel_case_types)]
                    struct CheckQRSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::CheckQrRequest>
                    for CheckQRSvc<T> {
                        type Response = super::QrStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckQrRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::check_qr(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckQRSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/GetCaptcha" => {
                    #[allow(non_camel_case_types)]
                    struct GetCaptchaSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::GetCaptchaRequest>
                    for GetCaptchaSvc<T> {
                        type Response = super::CaptchaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCaptchaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::get_captcha(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCaptchaSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/SendSMS" => {
                    #[allow(non_camel_case_types)]
                    struct SendSMSSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::SendSmsRequest>
                    for SendSMSSvc<T> {
                        type Response = super::SendSmsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendSmsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::send_sms(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendSMSSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/LoginSMS" => {
                    #[allow(non_camel_case_types)]
                    struct LoginSMSSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::LoginSmsRequest>
                    for LoginSMSSvc<T> {
                        type Response = super::LoginSmsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginSmsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::login_sms(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginSMSSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/GetUserInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserInfoSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::UserInfoRequest>
                    for GetUserInfoSvc<T> {
                        type Response = super::UserInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UserInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::get_user_info(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/Logout" => {
                    #[allow(non_camel_case_types)]
                    struct LogoutSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::LogoutRequest>
                    for LogoutSvc<T> {
                        type Response = super::LogoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::logout(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.provider.bilibili.BilibiliProviderService/GetBinds" => {
                    #[allow(non_camel_case_types)]
                    struct GetBindsSvc<T: BilibiliProviderService>(pub Arc<T>);
                    impl<
                        T: BilibiliProviderService,
                    > tonic::server::UnaryService<super::GetBindsRequest>
                    for GetBindsSvc<T> {
                        type Response = super::GetBindsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBindsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BilibiliProviderService>::get_binds(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBindsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BilibiliProviderServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "synctv.provider.bilibili.BilibiliProviderService";
    impl<T> tonic::server::NamedService for BilibiliProviderServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
