schema-version = 1

[source]
kind = "git"
repository = "https://github.com/synctv-org/synctv-app.git"
revision = "24109a49b2e27f7772d067fae66b622431c942d5"
commit = "24109a49b2e27f7772d067fae66b622431c942d5"

[build]
flutter = "flutter"
arguments = ["--release", "--no-web-resources-cdn", "--no-wasm-dry-run"]
