{{- if .Values.serviceAccount.create -}}
{{- $requiresServiceAccountToken := and .Values.metrics.enabled (eq (.Values.metrics.auth.mode | default "bearer_token") "kubernetes") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synctv.serviceAccountName" . }}
  labels:
    {{- include "synctv.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ ternary true .Values.serviceAccount.automount $requiresServiceAccountToken }}
{{- end }}
