[package]
name = "synctv-management"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["tls-aws-lc", "tls-webpki-roots"]
tls-aws-lc = [
    "synctv-cluster/tls-aws-lc",
    "synctv-core/tls-aws-lc",
    "synctv-proto/tls-aws-lc",
    "tonic/tls-aws-lc",
]
tls-ring = [
    "synctv-cluster/tls-ring",
    "synctv-core/tls-ring",
    "synctv-proto/tls-ring",
    "tonic/tls-ring",
]
tls-webpki-roots = [
    "synctv-cluster/tls-webpki-roots",
    "synctv-core/tls-webpki-roots",
    "synctv-proto/tls-webpki-roots",
    "tonic/tls-webpki-roots",
]
tls-native-roots = [
    "synctv-cluster/tls-native-roots",
    "synctv-core/tls-native-roots",
    "synctv-proto/tls-native-roots",
    "tonic/tls-native-roots",
]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
ipnet.workspace = true
prost.workspace = true
prost-types.workspace = true
pbjson.workspace = true
pbjson-types.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, features = ["net"] }
tonic.workspace = true
tonic-health.workspace = true
tonic-prost.workspace = true
tonic-reflection.workspace = true
tracing.workspace = true
synctv-adapter = { workspace = true, default-features = false }
synctv-cluster = { workspace = true, default-features = false }
synctv-common = { workspace = true, default-features = false }
synctv-core = { workspace = true, default-features = false }
synctv-proxy = { workspace = true, default-features = false }
synctv-proto = { workspace = true, default-features = false, features = ["main", "providers"] }
synctv-realtime = { workspace = true, default-features = false }

[build-dependencies]
pbjson-build.workspace = true
prost.workspace = true
prost-types.workspace = true
tonic-prost-build.workspace = true
