CREATE TABLE IF NOT EXISTS room_member_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    banned_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    reason TEXT,
    starts_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ends_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by BIGINT REFERENCES users(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_room_member_bans_active_unique
    ON room_member_bans(room_id, user_id)
    WHERE revoked_at IS NULL
      AND ends_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_room_member_bans_room
    ON room_member_bans(room_id, starts_at DESC);

CREATE INDEX IF NOT EXISTS idx_room_member_bans_user
    ON room_member_bans(user_id, starts_at DESC);

CREATE INDEX IF NOT EXISTS idx_room_member_bans_banned_by
    ON room_member_bans(banned_by, starts_at DESC)
    WHERE banned_by IS NOT NULL;

COMMENT ON TABLE room_member_bans IS 'Room-scoped member ban records';
