CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_id BIGINT,
    actor_username VARCHAR(50),
    action VARCHAR(50) NOT NULL,
    target_type VARCHAR(50),
    target_id VARCHAR(100),
    details JSONB,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS audit_logs_default PARTITION OF audit_logs DEFAULT;

CREATE INDEX IF NOT EXISTS audit_logs_default_idx_actor_created
    ON audit_logs_default(actor_id, created_at DESC)
    WHERE actor_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS audit_logs_default_idx_action_created
    ON audit_logs_default(action, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_default_idx_target_created
    ON audit_logs_default(target_type, target_id, created_at DESC)
    WHERE target_type IS NOT NULL;
CREATE INDEX IF NOT EXISTS audit_logs_default_idx_ip_address
    ON audit_logs_default(ip_address)
    WHERE ip_address IS NOT NULL;

CREATE OR REPLACE FUNCTION create_audit_logs_partition(
    partition_date DATE DEFAULT CURRENT_DATE
) RETURNS JSON AS $$
DECLARE
    normalized_month DATE := DATE_TRUNC('month', partition_date)::DATE;
    partition_name TEXT := 'audit_logs_' || TO_CHAR(normalized_month, 'YYYY_MM');
    start_date DATE := normalized_month;
    end_date DATE := (normalized_month + INTERVAL '1 month')::DATE;
BEGIN
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF audit_logs
         FOR VALUES FROM (%L) TO (%L)',
        partition_name, start_date, end_date
    );

    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I(actor_id, created_at DESC) WHERE actor_id IS NOT NULL',
        partition_name || '_idx_actor_created', partition_name
    );
    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I(action, created_at DESC)',
        partition_name || '_idx_action_created', partition_name
    );
    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I(target_type, target_id, created_at DESC) WHERE target_type IS NOT NULL',
        partition_name || '_idx_target_created', partition_name
    );
    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I(ip_address) WHERE ip_address IS NOT NULL',
        partition_name || '_idx_ip_address', partition_name
    );

    RETURN json_build_object(
        'partition_name', partition_name,
        'start_date', start_date::TEXT,
        'end_date', end_date::TEXT,
        'indexes_created', 4,
        'status', 'success'
    );
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION create_audit_logs_partitions(
    months_ahead INTEGER DEFAULT 6
) RETURNS JSON AS $$
DECLARE
    offset_month INTEGER;
    result JSON;
    partitions JSONB := '[]'::JSONB;
    total_requested INTEGER;
BEGIN
    IF months_ahead < 0 THEN
        RAISE EXCEPTION 'months_ahead must be greater than or equal to 0';
    END IF;

    total_requested := months_ahead + 1;

    FOR offset_month IN 0..months_ahead LOOP
        result := create_audit_logs_partition(
            (DATE_TRUNC('month', CURRENT_DATE) + make_interval(months => offset_month))::DATE
        );
        partitions := partitions || result::JSONB;
    END LOOP;

    RETURN json_build_object(
        'status', 'completed',
        'total_requested', total_requested,
        'success_count', total_requested,
        'partitions', partitions
    );
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION drop_old_audit_logs_partitions(
    keep_months INTEGER DEFAULT 12
) RETURNS JSON AS $$
DECLARE
    cutoff_name TEXT := 'audit_logs_' || TO_CHAR(
        (DATE_TRUNC('month', CURRENT_DATE) - make_interval(months => keep_months))::DATE,
        'YYYY_MM'
    );
    partition_record RECORD;
    dropped JSONB := '[]'::JSONB;
BEGIN
    FOR partition_record IN
        SELECT tablename
        FROM pg_tables
        WHERE schemaname = 'public'
          AND tablename ~ '^audit_logs_[0-9]{4}_[0-9]{2}$'
          AND tablename < cutoff_name
        ORDER BY tablename
    LOOP
        EXECUTE format('DROP TABLE IF EXISTS %I', partition_record.tablename);
        dropped := dropped || jsonb_build_array(
            jsonb_build_object('partition', partition_record.tablename)
        );
    END LOOP;

    RETURN json_build_object(
        'status', 'success',
        'dropped_count', jsonb_array_length(dropped),
        'keep_months', keep_months,
        'dropped_partitions', dropped
    );
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_audit_logs_partitions() RETURNS JSON AS $$
DECLARE
    expected_partition TEXT;
    missing_partitions JSONB := '[]'::JSONB;
    partition_record RECORD;
    total_partitions INTEGER := 0;
    total_size BIGINT := 0;
BEGIN
    FOR partition_record IN
        SELECT generate_series(0, 6) AS offset_month
    LOOP
        expected_partition := 'audit_logs_' || TO_CHAR(
            (DATE_TRUNC('month', CURRENT_DATE) + make_interval(months => partition_record.offset_month))::DATE,
            'YYYY_MM'
        );
        IF NOT EXISTS (
            SELECT 1
            FROM pg_tables
            WHERE schemaname = 'public'
              AND tablename = expected_partition
        ) THEN
            missing_partitions := missing_partitions || jsonb_build_array(
                jsonb_build_object('partition_name', expected_partition, 'status', 'missing')
            );
        END IF;
    END LOOP;

    FOR partition_record IN
        SELECT c.oid
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relkind = 'r'
          AND c.relname ~ '^audit_logs_[0-9]{4}_[0-9]{2}$'
    LOOP
        total_partitions := total_partitions + 1;
        total_size := total_size + pg_total_relation_size(partition_record.oid);
    END LOOP;

    RETURN json_build_object(
        'status', 'checked',
        'total_partitions', total_partitions,
        'total_size_mb', ROUND(total_size::NUMERIC / 1024 / 1024, 2),
        'total_size_gb', ROUND(total_size::NUMERIC / 1024 / 1024 / 1024, 2),
        'missing_partitions', missing_partitions,
        'missing_count', jsonb_array_length(missing_partitions),
        'health_status', CASE
            WHEN jsonb_array_length(missing_partitions) = 0 THEN 'healthy'
            ELSE 'warning'
        END
    );
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_audit_logs_stats() RETURNS JSON AS $$
DECLARE
    partition_record RECORD;
    partitions JSONB := '[]'::JSONB;
    total_partitions INTEGER := 0;
    total_records BIGINT := 0;
BEGIN
    FOR partition_record IN
        SELECT
            c.relname AS tablename,
            GREATEST(c.reltuples, 0)::BIGINT AS row_count,
            pg_total_relation_size(c.oid) AS size_bytes
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relkind = 'r'
          AND c.relname ~ '^audit_logs_[0-9]{4}_[0-9]{2}$'
        ORDER BY c.relname DESC
    LOOP
        partitions := partitions || jsonb_build_array(
            jsonb_build_object(
                'partition', partition_record.tablename,
                'row_count', partition_record.row_count,
                'size_mb', ROUND(partition_record.size_bytes::NUMERIC / 1024 / 1024, 2)
            )
        );
        total_partitions := total_partitions + 1;
        total_records := total_records + partition_record.row_count;
    END LOOP;

    RETURN json_build_object(
        'total_partitions', total_partitions,
        'total_records', total_records,
        'partitions', partitions
    );
END;
$$ LANGUAGE plpgsql;

SELECT create_audit_logs_partitions(6);
