CREATE TABLE IF NOT EXISTS auth_oauth2_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT auth_oauth2_identities_provider_subject_unique
        UNIQUE(provider, provider_user_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_oauth2_identities_user_id ON auth_oauth2_identities(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_oauth2_identities_provider ON auth_oauth2_identities(provider);

CREATE TRIGGER update_auth_oauth2_identities_updated_at
    BEFORE UPDATE ON auth_oauth2_identities
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
