CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id BIGINT NOT NULL,
    user_id BIGINT,
    content TEXT NOT NULL,
    message_type SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, created_at),
    FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS chat_messages_default PARTITION OF chat_messages DEFAULT;
CREATE INDEX IF NOT EXISTS chat_messages_default_idx_room_pagination
    ON chat_messages_default(room_id, created_at DESC, user_id);
CREATE INDEX IF NOT EXISTS chat_messages_default_idx_user_created
    ON chat_messages_default(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS chat_messages_default_idx_created_at
    ON chat_messages_default(created_at DESC);
