CREATE TABLE IF NOT EXISTS file_objects (
    storage_backend TEXT NOT NULL,
    object_key TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum_sha256 TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at TIMESTAMPTZ,
    PRIMARY KEY (storage_backend, object_key),
    UNIQUE (storage_backend, checksum_sha256, size_bytes),
    CHECK (length(storage_backend) BETWEEN 1 AND 64),
    CHECK (length(object_key) BETWEEN 1 AND 2048),
    CHECK (size_bytes > 0),
    CHECK (length(checksum_sha256) = 64),
    CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_file_objects_checksum
    ON file_objects(storage_backend, checksum_sha256, size_bytes);
CREATE INDEX IF NOT EXISTS idx_file_objects_validated
    ON file_objects(validated_at DESC);

CREATE TABLE IF NOT EXISTS file_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_backend TEXT NOT NULL,
    object_key TEXT NOT NULL,
    reference_kind TEXT NOT NULL,
    reference_id TEXT NOT NULL,
    expires_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (reference_kind, reference_id, storage_backend, object_key),
    CHECK (length(storage_backend) BETWEEN 1 AND 64),
    CHECK (length(object_key) BETWEEN 1 AND 2048),
    CHECK (length(reference_kind) BETWEEN 1 AND 64),
    CHECK (length(reference_id) BETWEEN 1 AND 256),
    CHECK (jsonb_typeof(metadata) = 'object'),
    FOREIGN KEY (storage_backend, object_key)
        REFERENCES file_objects(storage_backend, object_key) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_file_references_object_active
    ON file_references(storage_backend, object_key)
    WHERE released_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_file_references_expiry
    ON file_references(expires_at)
    WHERE released_at IS NULL AND expires_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS file_blobs (
    storage_backend TEXT NOT NULL,
    object_key TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum_sha256 TEXT NOT NULL,
    data BYTEA NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (storage_backend, object_key),
    CHECK (length(storage_backend) BETWEEN 1 AND 64),
    CHECK (length(object_key) BETWEEN 1 AND 2048),
    CHECK (size_bytes > 0),
    CHECK (octet_length(data) = size_bytes),
    CHECK (length(checksum_sha256) = 64),
    CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_file_blobs_created_at
    ON file_blobs(created_at DESC);

CREATE TABLE IF NOT EXISTS file_cleanup_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin TEXT NOT NULL,
    storage_backend TEXT NOT NULL,
    object_key TEXT NOT NULL,
    reference_kind TEXT NOT NULL,
    reference_id TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at TIMESTAMPTZ,
    locked_by TEXT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (reference_kind, reference_id, storage_backend, object_key),
    CHECK (length(origin) BETWEEN 1 AND 64),
    CHECK (length(storage_backend) BETWEEN 1 AND 64),
    CHECK (length(object_key) BETWEEN 1 AND 2048),
    CHECK (length(reference_kind) BETWEEN 1 AND 64),
    CHECK (length(reference_id) BETWEEN 1 AND 256),
    CHECK (attempt_count >= 0),
    CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_file_cleanup_jobs_due
    ON file_cleanup_jobs(next_attempt_at, id)
    WHERE completed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_file_cleanup_jobs_object
    ON file_cleanup_jobs(storage_backend, object_key)
    WHERE completed_at IS NULL;

ALTER TABLE users
    ADD CONSTRAINT users_avatar_file_reference_fk
    FOREIGN KEY (avatar_file_reference_id)
    REFERENCES file_references(id)
    ON DELETE SET NULL;

ALTER TABLE rooms
    ADD CONSTRAINT rooms_cover_file_reference_fk
    FOREIGN KEY (cover_file_reference_id)
    REFERENCES file_references(id)
    ON DELETE SET NULL;

ALTER TABLE playlists
    ADD CONSTRAINT playlists_cover_file_reference_fk
    FOREIGN KEY (cover_file_reference_id)
    REFERENCES file_references(id)
    ON DELETE SET NULL;

ALTER TABLE media
    ADD CONSTRAINT media_cover_file_reference_fk
    FOREIGN KEY (cover_file_reference_id)
    REFERENCES file_references(id)
    ON DELETE SET NULL;
