// This file is @generated by prost-build.
/// Node information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeInfo {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// gRPC address (host:port)
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
    /// Optional region/zone info
    #[prost(string, tag = "3")]
    pub region: ::prost::alloc::string::String,
    #[prost(enumeration = "NodeStatus", tag = "4")]
    pub status: i32,
    #[prost(int64, tag = "5")]
    pub registered_at: i64,
    #[prost(int64, tag = "6")]
    pub last_heartbeat: i64,
    #[prost(message, optional, tag = "7")]
    pub metrics: ::core::option::Option<NodeMetrics>,
    /// Fencing token epoch for stale-registration protection
    #[prost(uint64, tag = "8")]
    pub epoch: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NodeMetrics {
    #[prost(int32, tag = "1")]
    pub active_connections: i32,
    #[prost(int32, tag = "2")]
    pub active_streams: i32,
    #[prost(int32, tag = "3")]
    pub active_rooms: i32,
    #[prost(double, tag = "4")]
    pub cpu_usage: f64,
    #[prost(double, tag = "5")]
    pub memory_usage_mb: f64,
    #[prost(double, tag = "6")]
    pub network_bandwidth_mbps: f64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetNodesRequest {
    /// Optional filter
    #[prost(enumeration = "NodeStatus", tag = "1")]
    pub status_filter: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNodesResponse {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<NodeInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeregisterNodeRequest {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// shutdown, upgrade, failure, etc.
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    /// Fencing token epoch (required for stale-deregister protection)
    #[prost(uint64, tag = "3")]
    pub epoch: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeregisterNodeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// User connection tracking
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserOnlineStatusRequest {
    #[prost(int64, repeated, tag = "1")]
    pub user_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserOnlineStatusResponse {
    #[prost(message, repeated, tag = "1")]
    pub statuses: ::prost::alloc::vec::Vec<UserOnlineStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserOnlineStatus {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(bool, tag = "2")]
    pub is_online: bool,
    /// Rooms user is currently in
    #[prost(int64, repeated, tag = "3")]
    pub room_ids: ::prost::alloc::vec::Vec<i64>,
    /// Node where user is connected
    #[prost(string, tag = "4")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRoomConnectionsRequest {
    #[prost(int64, tag = "1")]
    pub room_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRoomConnectionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub connections: ::prost::alloc::vec::Vec<RoomConnection>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoomConnection {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub connected_at: i64,
    #[prost(int64, tag = "4")]
    pub last_activity: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeStatus {
    Unknown = 0,
    Active = 1,
    Draining = 2,
    Offline = 3,
}
impl NodeStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "NODE_STATUS_UNKNOWN",
            Self::Active => "NODE_STATUS_ACTIVE",
            Self::Draining => "NODE_STATUS_DRAINING",
            Self::Offline => "NODE_STATUS_OFFLINE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_STATUS_UNKNOWN" => Some(Self::Unknown),
            "NODE_STATUS_ACTIVE" => Some(Self::Active),
            "NODE_STATUS_DRAINING" => Some(Self::Draining),
            "NODE_STATUS_OFFLINE" => Some(Self::Offline),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod cluster_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Cluster coordination service for multi-replica deployment
    ///
    /// Architecture Overview:
    ///
    /// * Redis is the SOLE discovery mechanism for this cluster
    /// * Nodes self-register in Redis via NodeRegistry::register() on startup
    /// * Heartbeats are sent directly to Redis via NodeRegistry::heartbeat()
    /// * Events are broadcast via Redis Pub/Sub through ClusterManager
    ///
    /// Endpoint Usage:
    ///
    /// * GetNodes: ACTIVE - returns all known nodes from Redis registry
    /// * DeregisterNode: ACTIVE - handles graceful shutdown with epoch validation
    /// * GetUserOnlineStatus: ACTIVE - fan-out query for user presence
    /// * GetRoomConnections: ACTIVE - fan-out query for room participants
    #[derive(Debug, Clone)]
    pub struct ClusterServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ClusterServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ClusterServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ClusterServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ClusterServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Node discovery and shutdown
        pub async fn get_nodes(
            &mut self,
            request: impl tonic::IntoRequest<super::GetNodesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNodesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.cluster.ClusterService/GetNodes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("synctv.cluster.ClusterService", "GetNodes"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn deregister_node(
            &mut self,
            request: impl tonic::IntoRequest<super::DeregisterNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeregisterNodeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.cluster.ClusterService/DeregisterNode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("synctv.cluster.ClusterService", "DeregisterNode"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// User connection tracking - ACTIVE endpoints for fan-out queries
        pub async fn get_user_online_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserOnlineStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserOnlineStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.cluster.ClusterService/GetUserOnlineStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.cluster.ClusterService",
                        "GetUserOnlineStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_room_connections(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRoomConnectionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRoomConnectionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.cluster.ClusterService/GetRoomConnections",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.cluster.ClusterService",
                        "GetRoomConnections",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod cluster_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ClusterServiceServer.
    #[async_trait]
    pub trait ClusterService: std::marker::Send + std::marker::Sync + 'static {
        /// Node discovery and shutdown
        async fn get_nodes(
            &self,
            request: tonic::Request<super::GetNodesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNodesResponse>,
            tonic::Status,
        >;
        async fn deregister_node(
            &self,
            request: tonic::Request<super::DeregisterNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeregisterNodeResponse>,
            tonic::Status,
        >;
        /// User connection tracking - ACTIVE endpoints for fan-out queries
        async fn get_user_online_status(
            &self,
            request: tonic::Request<super::GetUserOnlineStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserOnlineStatusResponse>,
            tonic::Status,
        >;
        async fn get_room_connections(
            &self,
            request: tonic::Request<super::GetRoomConnectionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRoomConnectionsResponse>,
            tonic::Status,
        >;
    }
    /// Cluster coordination service for multi-replica deployment
    ///
    /// Architecture Overview:
    ///
    /// * Redis is the SOLE discovery mechanism for this cluster
    /// * Nodes self-register in Redis via NodeRegistry::register() on startup
    /// * Heartbeats are sent directly to Redis via NodeRegistry::heartbeat()
    /// * Events are broadcast via Redis Pub/Sub through ClusterManager
    ///
    /// Endpoint Usage:
    ///
    /// * GetNodes: ACTIVE - returns all known nodes from Redis registry
    /// * DeregisterNode: ACTIVE - handles graceful shutdown with epoch validation
    /// * GetUserOnlineStatus: ACTIVE - fan-out query for user presence
    /// * GetRoomConnections: ACTIVE - fan-out query for room participants
    #[derive(Debug)]
    pub struct ClusterServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ClusterServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ClusterServiceServer<T>
    where
        T: ClusterService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/synctv.cluster.ClusterService/GetNodes" => {
                    #[allow(non_camel_case_types)]
                    struct GetNodesSvc<T: ClusterService>(pub Arc<T>);
                    impl<
                        T: ClusterService,
                    > tonic::server::UnaryService<super::GetNodesRequest>
                    for GetNodesSvc<T> {
                        type Response = super::GetNodesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetNodesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClusterService>::get_nodes(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetNodesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.cluster.ClusterService/DeregisterNode" => {
                    #[allow(non_camel_case_types)]
                    struct DeregisterNodeSvc<T: ClusterService>(pub Arc<T>);
                    impl<
                        T: ClusterService,
                    > tonic::server::UnaryService<super::DeregisterNodeRequest>
                    for DeregisterNodeSvc<T> {
                        type Response = super::DeregisterNodeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeregisterNodeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClusterService>::deregister_node(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeregisterNodeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.cluster.ClusterService/GetUserOnlineStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserOnlineStatusSvc<T: ClusterService>(pub Arc<T>);
                    impl<
                        T: ClusterService,
                    > tonic::server::UnaryService<super::GetUserOnlineStatusRequest>
                    for GetUserOnlineStatusSvc<T> {
                        type Response = super::GetUserOnlineStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUserOnlineStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClusterService>::get_user_online_status(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserOnlineStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.cluster.ClusterService/GetRoomConnections" => {
                    #[allow(non_camel_case_types)]
                    struct GetRoomConnectionsSvc<T: ClusterService>(pub Arc<T>);
                    impl<
                        T: ClusterService,
                    > tonic::server::UnaryService<super::GetRoomConnectionsRequest>
                    for GetRoomConnectionsSvc<T> {
                        type Response = super::GetRoomConnectionsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRoomConnectionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ClusterService>::get_room_connections(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRoomConnectionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ClusterServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "synctv.cluster.ClusterService";
    impl<T> tonic::server::NamedService for ClusterServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
