//! Audit logging service
//!
//! Tracks admin actions and permission changes for compliance and debugging.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::PgPool;

use crate::Result;

/// Audit log entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditLog {
    pub id: String,
    pub actor_id: String,
    pub actor_username: String,
    pub action: AuditAction,
    pub target_type: AuditTargetType,
    pub target_id: Option<String>,
    pub details: serde_json::Value,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// Parameters for logging an audit event
#[derive(Debug, Clone)]
pub struct AuditEventParams {
    pub actor_id: String,
    pub actor_username: String,
    pub action: AuditAction,
    pub target_type: AuditTargetType,
    pub target_id: Option<String>,
    pub details: serde_json::Value,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
}

/// Audit actions
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuditAction {
    UserCreated,
    UserDeleted,
    UserBanned,
    UserUnbanned,
    UserPasswordUpdated,
    UserUsernameUpdated,
    UserRoleUpdated,
    RoomCreated,
    RoomDeleted,
    RoomBanned,
    RoomUnbanned,
    RoomPasswordUpdated,
    PermissionGranted,
    PermissionRevoked,
    ProviderInstanceCreated,
    ProviderInstanceUpdated,
    ProviderInstanceDeleted,
    SettingsUpdated,
}

impl AuditAction {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::UserCreated => "user_created",
            Self::UserDeleted => "user_deleted",
            Self::UserBanned => "user_banned",
            Self::UserUnbanned => "user_unbanned",
            Self::UserPasswordUpdated => "user_password_updated",
            Self::UserUsernameUpdated => "user_username_updated",
            Self::UserRoleUpdated => "user_role_updated",
            Self::RoomCreated => "room_created",
            Self::RoomDeleted => "room_deleted",
            Self::RoomBanned => "room_banned",
            Self::RoomUnbanned => "room_unbanned",
            Self::RoomPasswordUpdated => "room_password_updated",
            Self::PermissionGranted => "permission_granted",
            Self::PermissionRevoked => "permission_revoked",
            Self::ProviderInstanceCreated => "provider_instance_created",
            Self::ProviderInstanceUpdated => "provider_instance_updated",
            Self::ProviderInstanceDeleted => "provider_instance_deleted",
            Self::SettingsUpdated => "settings_updated",
        }
    }
}

/// Target types
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuditTargetType {
    User,
    Room,
    ProviderInstance,
    Settings,
    System,
}

impl AuditTargetType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::User => "user",
            Self::Room => "room",
            Self::ProviderInstance => "provider_instance",
            Self::Settings => "settings",
            Self::System => "system",
        }
    }
}

/// Audit logging service
///
/// Records audit logs for security-relevant actions.
pub struct AuditService {
    pool: PgPool,
}

impl AuditService {
    /// Create a new audit service
    #[must_use] 
    pub const fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Log an audit event
    #[allow(clippy::too_many_arguments)]
    pub async fn log(
        &self,
        actor_id: String,
        actor_username: String,
        action: AuditAction,
        target_type: AuditTargetType,
        target_id: Option<String>,
        details: serde_json::Value,
        ip_address: Option<String>,
        user_agent: Option<String>,
    ) -> Result<()> {
        let action_str = action.as_str();
        let target_str = target_type.as_str();
        let created_at = Utc::now();

        // Insert into database (id is BIGSERIAL, auto-generated by PostgreSQL)
        let query = r"
            INSERT INTO audit_logs (
                actor_id, actor_username, action, target_type, target_id,
                details, ip_address, user_agent, created_at
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ";

        sqlx::query(query)
            .bind(&actor_id)
            .bind(&actor_username)
            .bind(action_str)
            .bind(target_str)
            .bind(&target_id)
            .bind(&details)
            .bind(&ip_address)
            .bind(&user_agent)
            .bind(created_at)
            .execute(&self.pool)
            .await?;

        tracing::debug!(
            actor_id = %actor_id,
            action = %action_str,
            target_type = %target_str,
            "Audit log recorded"
        );

        Ok(())
    }

    /// Log an audit event with parameters struct
    pub async fn log_with_params(&self, params: AuditEventParams) -> Result<()> {
        self.log(
            params.actor_id,
            params.actor_username,
            params.action,
            params.target_type,
            params.target_id,
            params.details,
            params.ip_address,
            params.user_agent,
        )
        .await
    }

    /// Log user creation
    pub async fn log_user_created(
        &self,
        actor_id: String,
        actor_username: String,
        target_user_id: String,
    ) -> Result<()> {
        self.log(
            actor_id,
            actor_username,
            AuditAction::UserCreated,
            AuditTargetType::User,
            Some(target_user_id),
            serde_json::json!({"reason": "User created via admin panel"}),
            None,
            None,
        )
        .await
    }

    /// Log user ban
    pub async fn log_user_banned(
        &self,
        actor_id: String,
        actor_username: String,
        target_user_id: String,
    ) -> Result<()> {
        self.log(
            actor_id,
            actor_username,
            AuditAction::UserBanned,
            AuditTargetType::User,
            Some(target_user_id),
            serde_json::json!({"reason": "User banned by admin"}),
            None,
            None,
        )
        .await
    }

    /// Log permission change
    ///
    /// The `is_grant` parameter determines the audit action:
    /// - `true` => `AuditAction::PermissionGranted`
    /// - `false` => `AuditAction::PermissionRevoked`
    pub async fn log_permission_changed(
        &self,
        actor_id: String,
        actor_username: String,
        target_type: AuditTargetType,
        target_id: String,
        old_permissions: u64,
        new_permissions: u64,
        is_grant: bool,
    ) -> Result<()> {
        let action = if is_grant {
            AuditAction::PermissionGranted
        } else {
            AuditAction::PermissionRevoked
        };

        self.log(
            actor_id,
            actor_username,
            action,
            target_type,
            Some(target_id),
            serde_json::json!({
                "old_permissions": old_permissions,
                "new_permissions": new_permissions
            }),
            None,
            None,
        )
        .await
    }

    /// Log room deletion
    pub async fn log_room_deleted(
        &self,
        actor_id: String,
        actor_username: String,
        room_id: String,
    ) -> Result<()> {
        self.log(
            actor_id,
            actor_username,
            AuditAction::RoomDeleted,
            AuditTargetType::Room,
            Some(room_id),
            serde_json::json!({"reason": "Room deleted by admin"}),
            None,
            None,
        )
        .await
    }
}

impl std::fmt::Debug for AuditService {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("AuditService").finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ========== AuditAction Serialization ==========

    #[test]
    fn test_audit_action_serialization() {
        let action = AuditAction::UserCreated;
        let json = serde_json::to_string(&action).unwrap();
        assert!(json.contains("user_created"));
    }

    #[test]
    fn test_all_audit_actions_serialize_to_snake_case() {
        let actions = vec![
            (AuditAction::UserCreated, "user_created"),
            (AuditAction::UserDeleted, "user_deleted"),
            (AuditAction::UserBanned, "user_banned"),
            (AuditAction::UserUnbanned, "user_unbanned"),
            (AuditAction::UserPasswordUpdated, "user_password_updated"),
            (AuditAction::UserUsernameUpdated, "user_username_updated"),
            (AuditAction::UserRoleUpdated, "user_role_updated"),
            (AuditAction::RoomCreated, "room_created"),
            (AuditAction::RoomDeleted, "room_deleted"),
            (AuditAction::RoomBanned, "room_banned"),
            (AuditAction::RoomUnbanned, "room_unbanned"),
            (AuditAction::RoomPasswordUpdated, "room_password_updated"),
            (AuditAction::PermissionGranted, "permission_granted"),
            (AuditAction::PermissionRevoked, "permission_revoked"),
            (AuditAction::ProviderInstanceCreated, "provider_instance_created"),
            (AuditAction::ProviderInstanceUpdated, "provider_instance_updated"),
            (AuditAction::ProviderInstanceDeleted, "provider_instance_deleted"),
            (AuditAction::SettingsUpdated, "settings_updated"),
        ];

        for (action, expected) in actions {
            let json = serde_json::to_string(&action).unwrap();
            assert_eq!(json, format!("\"{expected}\""), "Mismatch for {expected}");
        }
    }

    #[test]
    fn test_audit_action_deserialization() {
        let json = r#""user_banned""#;
        let action: AuditAction = serde_json::from_str(json).unwrap();
        assert!(matches!(action, AuditAction::UserBanned));
    }

    #[test]
    fn test_audit_action_round_trip() {
        let original = AuditAction::PermissionGranted;
        let json = serde_json::to_string(&original).unwrap();
        let deserialized: AuditAction = serde_json::from_str(&json).unwrap();
        assert_eq!(original.as_str(), deserialized.as_str());
    }

    // ========== AuditAction::as_str ==========

    #[test]
    fn test_audit_action_as_str_matches_serialization() {
        let actions = vec![
            AuditAction::UserCreated,
            AuditAction::UserDeleted,
            AuditAction::UserBanned,
            AuditAction::UserUnbanned,
            AuditAction::UserPasswordUpdated,
            AuditAction::UserUsernameUpdated,
            AuditAction::UserRoleUpdated,
            AuditAction::RoomCreated,
            AuditAction::RoomDeleted,
            AuditAction::RoomBanned,
            AuditAction::RoomUnbanned,
            AuditAction::RoomPasswordUpdated,
            AuditAction::PermissionGranted,
            AuditAction::PermissionRevoked,
            AuditAction::ProviderInstanceCreated,
            AuditAction::ProviderInstanceUpdated,
            AuditAction::ProviderInstanceDeleted,
            AuditAction::SettingsUpdated,
        ];

        for action in actions {
            let as_str = action.as_str();
            let serialized = serde_json::to_string(&action).unwrap();
            // Serialized form is quoted: "user_created"
            assert_eq!(serialized, format!("\"{as_str}\""));
        }
    }

    // ========== AuditTargetType ==========

    #[test]
    fn test_all_target_types_serialize_to_snake_case() {
        let targets = vec![
            (AuditTargetType::User, "user"),
            (AuditTargetType::Room, "room"),
            (AuditTargetType::ProviderInstance, "provider_instance"),
            (AuditTargetType::Settings, "settings"),
            (AuditTargetType::System, "system"),
        ];

        for (target, expected) in targets {
            let json = serde_json::to_string(&target).unwrap();
            assert_eq!(json, format!("\"{expected}\""), "Mismatch for {expected}");
        }
    }

    #[test]
    fn test_target_type_as_str_matches_serialization() {
        let targets = vec![
            AuditTargetType::User,
            AuditTargetType::Room,
            AuditTargetType::ProviderInstance,
            AuditTargetType::Settings,
            AuditTargetType::System,
        ];

        for target in targets {
            let as_str = target.as_str();
            let serialized = serde_json::to_string(&target).unwrap();
            assert_eq!(serialized, format!("\"{as_str}\""));
        }
    }

    #[test]
    fn test_target_type_deserialization() {
        let json = r#""provider_instance""#;
        let target: AuditTargetType = serde_json::from_str(json).unwrap();
        assert!(matches!(target, AuditTargetType::ProviderInstance));
    }

    // ========== AuditLog Construction ==========

    #[test]
    fn test_audit_log_construction() {
        let log = AuditLog {
            id: "test_id".to_string(),
            actor_id: "actor_123".to_string(),
            actor_username: "admin".to_string(),
            action: AuditAction::UserBanned,
            target_type: AuditTargetType::User,
            target_id: Some("user_456".to_string()),
            details: serde_json::json!({"reason": "spam"}),
            ip_address: Some("192.168.1.1".to_string()),
            user_agent: Some("Mozilla/5.0".to_string()),
            created_at: Utc::now(),
        };

        assert_eq!(log.id, "test_id");
        assert_eq!(log.actor_id, "actor_123");
        assert_eq!(log.actor_username, "admin");
        assert_eq!(log.action.as_str(), "user_banned");
        assert_eq!(log.target_type.as_str(), "user");
        assert_eq!(log.target_id, Some("user_456".to_string()));
        assert_eq!(log.details["reason"], "spam");
    }

    #[test]
    fn test_audit_log_optional_fields() {
        let log = AuditLog {
            id: "test".to_string(),
            actor_id: "system".to_string(),
            actor_username: "system".to_string(),
            action: AuditAction::SettingsUpdated,
            target_type: AuditTargetType::Settings,
            target_id: None,
            details: serde_json::json!({}),
            ip_address: None,
            user_agent: None,
            created_at: Utc::now(),
        };

        assert!(log.target_id.is_none());
        assert!(log.ip_address.is_none());
        assert!(log.user_agent.is_none());
    }

    #[test]
    fn test_audit_log_serialization_round_trip() {
        let log = AuditLog {
            id: "audit_1".to_string(),
            actor_id: "user_1".to_string(),
            actor_username: "alice".to_string(),
            action: AuditAction::RoomCreated,
            target_type: AuditTargetType::Room,
            target_id: Some("room_1".to_string()),
            details: serde_json::json!({"room_name": "Test Room"}),
            ip_address: Some("10.0.0.1".to_string()),
            user_agent: Some("TestAgent/1.0".to_string()),
            created_at: Utc::now(),
        };

        let json = serde_json::to_string(&log).unwrap();
        let deserialized: AuditLog = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.id, log.id);
        assert_eq!(deserialized.actor_id, log.actor_id);
        assert_eq!(deserialized.actor_username, log.actor_username);
        assert_eq!(deserialized.action.as_str(), log.action.as_str());
        assert_eq!(deserialized.target_type.as_str(), log.target_type.as_str());
        assert_eq!(deserialized.target_id, log.target_id);
        assert_eq!(deserialized.details, log.details);
    }

    // ========== AuditEventParams ==========

    #[test]
    fn test_audit_event_params_construction() {
        let params = AuditEventParams {
            actor_id: "admin_1".to_string(),
            actor_username: "superadmin".to_string(),
            action: AuditAction::UserRoleUpdated,
            target_type: AuditTargetType::User,
            target_id: Some("user_42".to_string()),
            details: serde_json::json!({
                "old_role": "user",
                "new_role": "admin"
            }),
            ip_address: Some("203.0.113.50".to_string()),
            user_agent: None,
        };

        assert_eq!(params.actor_id, "admin_1");
        assert_eq!(params.action.as_str(), "user_role_updated");
        assert_eq!(params.details["old_role"], "user");
        assert_eq!(params.details["new_role"], "admin");
    }

    // ========== Details JSON Formatting ==========

    #[test]
    fn test_permission_change_details_format() {
        let details = serde_json::json!({
            "old_permissions": 0u64,
            "new_permissions": 255u64
        });

        assert_eq!(details["old_permissions"], 0);
        assert_eq!(details["new_permissions"], 255);
    }

    #[test]
    fn test_details_with_nested_info() {
        let details = serde_json::json!({
            "reason": "Terms of service violation",
            "evidence": {
                "report_id": "rpt_123",
                "reported_by": ["user_a", "user_b"]
            },
            "duration": "permanent"
        });

        assert_eq!(details["reason"], "Terms of service violation");
        assert!(details["evidence"]["reported_by"].is_array());
        assert_eq!(details["evidence"]["reported_by"].as_array().unwrap().len(), 2);
    }

    // ========== Integration Tests (Require DB) ==========

    #[tokio::test]
    #[ignore = "Requires database"]
    async fn test_log_audit_event() {
        // Integration test placeholder
    }

    #[tokio::test]
    #[ignore = "Requires database"]
    async fn test_log_with_params() {
        // Integration test placeholder
    }
}
