[package]
name = "synctv-proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["full", "tls-aws-lc", "tls-webpki-roots"]
full = ["main", "providers", "playback-provider"]
main = []
providers = ["main"]
playback-provider = []
openapi = ["dep:utoipa"]
tls-aws-lc = ["tonic/tls-aws-lc"]
tls-ring = ["tonic/tls-ring"]
tls-webpki-roots = ["tonic/tls-webpki-roots"]
tls-native-roots = ["tonic/tls-native-roots"]

[lints]
workspace = true

[dependencies]
# gRPC
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
prost-types.workspace = true
prost-reflect.workspace = true
prost-protovalidate.workspace = true
pbjson.workspace = true
pbjson-types.workspace = true

# Serialization
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
utoipa = { workspace = true, optional = true }

[dev-dependencies]
serde_urlencoded.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
protoc-bin-vendored.workspace = true
prost-reflect-build.workspace = true
pbjson-build.workspace = true
prost.workspace = true
prost-types.workspace = true
