syntax = "proto3";

package synctv.provider.nextcloud;

import "proto/providers/nextcloud.proto";
import "proto/providers/common.proto";

service NextcloudProviderService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc StartLoginFlow(StartLoginFlowRequest) returns (StartLoginFlowResponse);
  rpc PollLoginFlow(PollLoginFlowRequest) returns (LoginResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc ListFavorites(ListFavoritesRequest) returns (ListResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc GetBinds(GetBindsRequest) returns (GetBindsResponse);
  rpc GetPreview(GetPreviewRequest) returns (stream synctv.provider.common.ResourceResponse);
}
