syntax = "proto3";

package synctv.provider.rtmp;

import "proto/buf/validate/validate.proto";

message CreatePublishKeyRequest {
  string room_id = 1 [(buf.validate.field).string = {
    min_len: 1
    max_len: 64
    pattern: "^room_[A-Za-z0-9]+$"
  }];
  string media_id = 2 [(buf.validate.field).string = {
    min_len: 1
    max_len: 64
    pattern: "^med_[A-Za-z0-9]+$"
  }];
}

message CreatePublishKeyResponse {
  string publish_key = 1;
  string rtmp_url = 2;
  string stream_key = 3;
  int64 expires_at = 4;
}

message GetStreamInfoRequest {
  string room_id = 1 [(buf.validate.field).string = {
    min_len: 1
    max_len: 64
    pattern: "^room_[A-Za-z0-9]+$"
  }];
  string media_id = 2 [(buf.validate.field).string = {
    min_len: 1
    max_len: 64
    pattern: "^med_[A-Za-z0-9]+$"
  }];
}

message StreamPublisherInfo {
  string user_id = 1;
  int64 started_at = 2;
}

message GetStreamInfoResponse {
  bool active = 1;
  StreamPublisherInfo publisher = 2;
}
