syntax = "proto3";

package synctv.provider.seafile;

import "proto/providers/seafile.proto";
import "proto/providers/common.proto";

service SeafileProviderService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc UnlockLibrary(UnlockLibraryRequest) returns (UnlockLibraryResponse);
  rpc ListRepositories(ListRepositoriesRequest) returns (ListResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc ListStarred(ListStarredRequest) returns (ListResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc GetBinds(GetBindsRequest) returns (GetBindsResponse);
  rpc GetThumbnail(GetThumbnailRequest) returns (stream synctv.provider.common.ResourceResponse);
}
