[package]
name = "synctv-core-testing"
version.workspace = true
edition.workspace = true

[dependencies]
synctv-core = { path = ".." }

sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "chrono", "uuid", "json"] }
testcontainers = { workspace = true, features = ["reusable-containers"] }
testcontainers-modules = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
chrono = { workspace = true }
nanoid = { workspace = true }
redis = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[features]
default = []
docker = []

[lib]
name = "synctv_core_testing"
path = "src/lib.rs"
