syntax = "proto3";

package synctv.playback_provider.emby;

import "proto/buf/validate/validate.proto";
import "proto/playback_provider/common.proto";

enum EmbyHlsResourceKind {
  EMBY_HLS_RESOURCE_KIND_UNSPECIFIED = 0;
  EMBY_HLS_RESOURCE_KIND_MEDIA = 1;
  EMBY_HLS_RESOURCE_KIND_MANIFEST = 2;
}

message GetEmbyMediaStreamRequest {
  string version = 1 [(buf.validate.field).string.min_len = 1];
  string mode_name = 2 [(buf.validate.field).string.min_len = 1];
  uint32 url_index = 3;
  string sig = 4 [(buf.validate.field).string.min_len = 1];
  string uid = 5 [(buf.validate.field).string.min_len = 1];
  string rid = 6 [(buf.validate.field).string.min_len = 1];
  int64 exp = 7;
  optional string range = 8;
  bool head = 9;
}

message EmbyMediaStreamResponse {
  synctv.playback_provider.common.StreamChunk chunk = 1;
}

message GetEmbyHlsManifestRequest {
  string version = 1 [(buf.validate.field).string.min_len = 1];
  string mode_name = 2 [(buf.validate.field).string.min_len = 1];
  uint32 url_index = 3;
  string sig = 4 [(buf.validate.field).string.min_len = 1];
  string uid = 5 [(buf.validate.field).string.min_len = 1];
  string rid = 6 [(buf.validate.field).string.min_len = 1];
  int64 exp = 7;
}

message EmbyHlsManifestResponse {
  synctv.playback_provider.common.StreamChunk chunk = 1;
}

message GetEmbyHlsResourceRequest {
  string version = 1 [(buf.validate.field).string.min_len = 1];
  string target_url = 2 [(buf.validate.field).string.min_len = 1];
  string sig = 3 [(buf.validate.field).string.min_len = 1];
  string uid = 4 [(buf.validate.field).string.min_len = 1];
  string rid = 5 [(buf.validate.field).string.min_len = 1];
  int64 exp = 6;
  optional string range = 7;
  bool head = 8;
  string mode_name = 9 [(buf.validate.field).string.min_len = 1];
  uint32 media_index = 10;
  EmbyHlsResourceKind resource_kind = 11 [(buf.validate.field).enum.defined_only = true];
}

message EmbyHlsResourceResponse {
  synctv.playback_provider.common.StreamChunk chunk = 1;
}

message GetEmbySubtitleRequest {
  string version = 1 [(buf.validate.field).string.min_len = 1];
  string mode_name = 2 [(buf.validate.field).string.min_len = 1];
  uint32 subtitle_index = 3;
  string sig = 4 [(buf.validate.field).string.min_len = 1];
  string uid = 5 [(buf.validate.field).string.min_len = 1];
  string rid = 6 [(buf.validate.field).string.min_len = 1];
  int64 exp = 7;
}

message EmbySubtitleResponse {
  synctv.playback_provider.common.StreamChunk chunk = 1;
}

service EmbyPlaybackProviderService {
  rpc GetMediaStream(GetEmbyMediaStreamRequest) returns (stream EmbyMediaStreamResponse);
  rpc GetHlsManifest(GetEmbyHlsManifestRequest) returns (stream EmbyHlsManifestResponse);
  rpc GetHlsResource(GetEmbyHlsResourceRequest) returns (stream EmbyHlsResourceResponse);
  rpc GetSubtitle(GetEmbySubtitleRequest) returns (stream EmbySubtitleResponse);
}
