[package]
name = "synctv-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
http-acl.workspace = true
http-acl-reqwest.workspace = true
ipnet.workspace = true
reqwest.workspace = true
tracing.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
iana-time-zone.workspace = true
nanoid.workspace = true

[lints]
workspace = true
