// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub hashed: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResp {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FsGetReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub user_agent: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FsGetResp {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size: u64,
    #[prost(bool, tag = "3")]
    pub is_dir: bool,
    #[prost(uint64, tag = "4")]
    pub modified: u64,
    #[prost(uint64, tag = "5")]
    pub created: u64,
    #[prost(string, tag = "6")]
    pub sign: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub thumb: ::prost::alloc::string::String,
    #[prost(uint64, tag = "8")]
    pub r#type: u64,
    #[prost(string, tag = "9")]
    pub hashinfo: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub raw_url: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub readme: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub provider: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "13")]
    pub related: ::prost::alloc::vec::Vec<fs_get_resp::FsGetRelated>,
}
/// Nested message and enum types in `FsGetResp`.
pub mod fs_get_resp {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct FsGetRelated {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(uint64, tag = "2")]
        pub size: u64,
        #[prost(bool, tag = "3")]
        pub is_dir: bool,
        #[prost(uint64, tag = "4")]
        pub modified: u64,
        #[prost(uint64, tag = "5")]
        pub created: u64,
        #[prost(string, tag = "6")]
        pub sign: ::prost::alloc::string::String,
        #[prost(string, tag = "7")]
        pub thumb: ::prost::alloc::string::String,
        #[prost(uint64, tag = "8")]
        pub r#type: u64,
        #[prost(string, tag = "9")]
        pub hashinfo: ::prost::alloc::string::String,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FsListReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub page: u64,
    #[prost(uint64, tag = "6")]
    pub per_page: u64,
    #[prost(bool, tag = "7")]
    pub refresh: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FsListResp {
    #[prost(message, repeated, tag = "1")]
    pub content: ::prost::alloc::vec::Vec<fs_list_resp::FsListContent>,
    #[prost(uint64, tag = "2")]
    pub total: u64,
    #[prost(string, tag = "3")]
    pub readme: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub write: bool,
    #[prost(string, tag = "5")]
    pub provider: ::prost::alloc::string::String,
}
/// Nested message and enum types in `FsListResp`.
pub mod fs_list_resp {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct FsListContent {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(uint64, tag = "2")]
        pub size: u64,
        #[prost(bool, tag = "3")]
        pub is_dir: bool,
        #[prost(uint64, tag = "4")]
        pub modified: u64,
        #[prost(string, tag = "6")]
        pub sign: ::prost::alloc::string::String,
        #[prost(string, tag = "7")]
        pub thumb: ::prost::alloc::string::String,
        #[prost(uint64, tag = "8")]
        pub r#type: u64,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FsOtherReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub password: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FsOtherResp {
    #[prost(string, tag = "1")]
    pub drive_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub video_preview_play_info: ::core::option::Option<
        fs_other_resp::VideoPreviewPlayInfo,
    >,
}
/// Nested message and enum types in `FsOtherResp`.
pub mod fs_other_resp {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct VideoPreviewPlayInfo {
        #[prost(string, tag = "1")]
        pub category: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub live_transcoding_subtitle_task_list: ::prost::alloc::vec::Vec<
            video_preview_play_info::LiveTranscodingSubtitleTaskList,
        >,
        #[prost(message, repeated, tag = "3")]
        pub live_transcoding_task_list: ::prost::alloc::vec::Vec<
            video_preview_play_info::LiveTranscodingTaskList,
        >,
        #[prost(message, optional, tag = "4")]
        pub meta: ::core::option::Option<video_preview_play_info::Meta>,
    }
    /// Nested message and enum types in `VideoPreviewPlayInfo`.
    pub mod video_preview_play_info {
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct LiveTranscodingSubtitleTaskList {
            #[prost(string, tag = "1")]
            pub language: ::prost::alloc::string::String,
            #[prost(string, tag = "2")]
            pub status: ::prost::alloc::string::String,
            #[prost(string, tag = "3")]
            pub url: ::prost::alloc::string::String,
        }
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct LiveTranscodingTaskList {
            #[prost(string, tag = "1")]
            pub stage: ::prost::alloc::string::String,
            #[prost(string, tag = "2")]
            pub status: ::prost::alloc::string::String,
            #[prost(uint64, tag = "3")]
            pub template_height: u64,
            #[prost(string, tag = "4")]
            pub template_id: ::prost::alloc::string::String,
            #[prost(string, tag = "5")]
            pub template_name: ::prost::alloc::string::String,
            #[prost(uint64, tag = "6")]
            pub template_width: u64,
            #[prost(string, tag = "7")]
            pub url: ::prost::alloc::string::String,
        }
        #[derive(serde::Serialize, serde::Deserialize)]
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct Meta {
            #[prost(double, tag = "1")]
            pub duration: f64,
            #[prost(uint64, tag = "2")]
            pub height: u64,
            #[prost(uint64, tag = "3")]
            pub width: u64,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MeReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MeResp {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub base_path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub role: u64,
    #[prost(bool, tag = "6")]
    pub disabled: bool,
    #[prost(uint64, tag = "7")]
    pub permission: u64,
    #[prost(string, tag = "8")]
    pub sso_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "9")]
    pub otp: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FsSearchReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub keywords: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub scope: u64,
    #[prost(uint64, tag = "6")]
    pub page: u64,
    #[prost(uint64, tag = "7")]
    pub per_page: u64,
    #[prost(string, tag = "8")]
    pub password: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FsSearchResp {
    #[prost(message, repeated, tag = "1")]
    pub content: ::prost::alloc::vec::Vec<fs_search_resp::FsSearchContent>,
    #[prost(uint64, tag = "2")]
    pub total: u64,
}
/// Nested message and enum types in `FsSearchResp`.
pub mod fs_search_resp {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct FsSearchContent {
        #[prost(string, tag = "1")]
        pub parent: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub name: ::prost::alloc::string::String,
        #[prost(bool, tag = "3")]
        pub is_dir: bool,
        #[prost(uint64, tag = "4")]
        pub size: u64,
        #[prost(uint64, tag = "5")]
        pub r#type: u64,
    }
}
/// Generated client implementations.
pub mod alist_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AlistClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AlistClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AlistClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AlistClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AlistClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn login(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginReq>,
        ) -> std::result::Result<tonic::Response<super::LoginResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.media.alist.Alist/Login",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("synctv.media.alist.Alist", "Login"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn me(
            &mut self,
            request: impl tonic::IntoRequest<super::MeReq>,
        ) -> std::result::Result<tonic::Response<super::MeResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.media.alist.Alist/Me",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("synctv.media.alist.Alist", "Me"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn fs_get(
            &mut self,
            request: impl tonic::IntoRequest<super::FsGetReq>,
        ) -> std::result::Result<tonic::Response<super::FsGetResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.media.alist.Alist/FsGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("synctv.media.alist.Alist", "FsGet"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn fs_list(
            &mut self,
            request: impl tonic::IntoRequest<super::FsListReq>,
        ) -> std::result::Result<tonic::Response<super::FsListResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.media.alist.Alist/FsList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("synctv.media.alist.Alist", "FsList"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn fs_other(
            &mut self,
            request: impl tonic::IntoRequest<super::FsOtherReq>,
        ) -> std::result::Result<tonic::Response<super::FsOtherResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.media.alist.Alist/FsOther",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("synctv.media.alist.Alist", "FsOther"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn fs_search(
            &mut self,
            request: impl tonic::IntoRequest<super::FsSearchReq>,
        ) -> std::result::Result<tonic::Response<super::FsSearchResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.media.alist.Alist/FsSearch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("synctv.media.alist.Alist", "FsSearch"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod alist_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AlistServer.
    #[async_trait]
    pub trait Alist: std::marker::Send + std::marker::Sync + 'static {
        async fn login(
            &self,
            request: tonic::Request<super::LoginReq>,
        ) -> std::result::Result<tonic::Response<super::LoginResp>, tonic::Status>;
        async fn me(
            &self,
            request: tonic::Request<super::MeReq>,
        ) -> std::result::Result<tonic::Response<super::MeResp>, tonic::Status>;
        async fn fs_get(
            &self,
            request: tonic::Request<super::FsGetReq>,
        ) -> std::result::Result<tonic::Response<super::FsGetResp>, tonic::Status>;
        async fn fs_list(
            &self,
            request: tonic::Request<super::FsListReq>,
        ) -> std::result::Result<tonic::Response<super::FsListResp>, tonic::Status>;
        async fn fs_other(
            &self,
            request: tonic::Request<super::FsOtherReq>,
        ) -> std::result::Result<tonic::Response<super::FsOtherResp>, tonic::Status>;
        async fn fs_search(
            &self,
            request: tonic::Request<super::FsSearchReq>,
        ) -> std::result::Result<tonic::Response<super::FsSearchResp>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct AlistServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AlistServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AlistServer<T>
    where
        T: Alist,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/synctv.media.alist.Alist/Login" => {
                    #[allow(non_camel_case_types)]
                    struct LoginSvc<T: Alist>(pub Arc<T>);
                    impl<T: Alist> tonic::server::UnaryService<super::LoginReq>
                    for LoginSvc<T> {
                        type Response = super::LoginResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Alist>::login(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.media.alist.Alist/Me" => {
                    #[allow(non_camel_case_types)]
                    struct MeSvc<T: Alist>(pub Arc<T>);
                    impl<T: Alist> tonic::server::UnaryService<super::MeReq>
                    for MeSvc<T> {
                        type Response = super::MeResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MeReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Alist>::me(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.media.alist.Alist/FsGet" => {
                    #[allow(non_camel_case_types)]
                    struct FsGetSvc<T: Alist>(pub Arc<T>);
                    impl<T: Alist> tonic::server::UnaryService<super::FsGetReq>
                    for FsGetSvc<T> {
                        type Response = super::FsGetResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FsGetReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Alist>::fs_get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FsGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.media.alist.Alist/FsList" => {
                    #[allow(non_camel_case_types)]
                    struct FsListSvc<T: Alist>(pub Arc<T>);
                    impl<T: Alist> tonic::server::UnaryService<super::FsListReq>
                    for FsListSvc<T> {
                        type Response = super::FsListResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FsListReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Alist>::fs_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FsListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.media.alist.Alist/FsOther" => {
                    #[allow(non_camel_case_types)]
                    struct FsOtherSvc<T: Alist>(pub Arc<T>);
                    impl<T: Alist> tonic::server::UnaryService<super::FsOtherReq>
                    for FsOtherSvc<T> {
                        type Response = super::FsOtherResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FsOtherReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Alist>::fs_other(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FsOtherSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.media.alist.Alist/FsSearch" => {
                    #[allow(non_camel_case_types)]
                    struct FsSearchSvc<T: Alist>(pub Arc<T>);
                    impl<T: Alist> tonic::server::UnaryService<super::FsSearchReq>
                    for FsSearchSvc<T> {
                        type Response = super::FsSearchResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FsSearchReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Alist>::fs_search(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FsSearchSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AlistServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "synctv.media.alist.Alist";
    impl<T> tonic::server::NamedService for AlistServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
