// This file is @generated by prost-build.
/// Login request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    /// Target Emby/Jellyfin username to bind and validate
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "5")]
    pub instance_name: ::prost::alloc::string::String,
    #[prost(oneof = "login_request::Credential", tags = "3, 4")]
    pub credential: ::core::option::Option<login_request::Credential>,
}
/// Nested message and enum types in `LoginRequest`.
pub mod login_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Credential {
        /// SECURITY: Plaintext password - requires TLS in transit.
        #[prost(string, tag = "3")]
        Password(::prost::alloc::string::String),
        /// SECURITY: Plaintext credential - requires TLS in transit.
        #[prost(string, tag = "4")]
        ApiKey(::prost::alloc::string::String),
    }
}
/// Login response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_admin: bool,
    /// SHA-256(host) identifier for stored credential
    #[prost(string, tag = "4")]
    pub server_id: ::prost::alloc::string::String,
}
/// List items request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    /// Stored credential identifier
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub start_index: u64,
    #[prost(uint64, tag = "4")]
    pub limit: u64,
    #[prost(string, tag = "5")]
    pub search_term: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "6")]
    pub instance_name: ::prost::alloc::string::String,
}
/// List items response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<MediaItem>,
    #[prost(uint64, tag = "2")]
    pub total: u64,
}
/// Media item information
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MediaItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub series_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub series_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub season_name: ::prost::alloc::string::String,
}
/// Get user info request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeRequest {
    /// Stored credential identifier
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get user info response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
/// Logout request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
    /// Which credential to unbind
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Logout response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Get binds request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBindsRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get binds response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBindsResponse {
    #[prost(message, repeated, tag = "1")]
    pub binds: ::prost::alloc::vec::Vec<BindInfo>,
}
/// Saved credential information
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    /// Unix epoch timestamp
    #[prost(int64, tag = "4")]
    pub created_at: i64,
}
