// This file is @generated by prost-build.
/// Parse video URL request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParseRequest {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    /// Stored credential identifier (use stored cookies)
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "3")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Parse video URL response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseResponse {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub actors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub videos: ::prost::alloc::vec::Vec<VideoInfo>,
}
/// Video information
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VideoInfo {
    #[prost(string, tag = "1")]
    pub bvid: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub cid: i64,
    #[prost(int64, tag = "3")]
    pub epid: i64,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub cover: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub is_live: bool,
}
/// QR code login request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginQrRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
}
/// QR code response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QrCodeResponse {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
/// Check QR status request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckQrRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    pub instance_name: ::prost::alloc::string::String,
}
/// QR status response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QrStatusResponse {
    #[prost(enumeration = "QrLoginStatus", tag = "1")]
    pub status: i32,
    /// Stored credential identifier returned after successful login
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
}
/// Get captcha request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCaptchaRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Captcha response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptchaResponse {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub gt: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub challenge: ::prost::alloc::string::String,
}
/// Send SMS request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendSmsRequest {
    #[prost(string, tag = "1")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub challenge: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub validate: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "5")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Send SMS response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendSmsResponse {
    #[prost(string, tag = "1")]
    pub captcha_key: ::prost::alloc::string::String,
}
/// Login with SMS request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSmsRequest {
    #[prost(string, tag = "1")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub captcha_key: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "4")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Login with SMS response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSmsResponse {
    /// Stored credential identifier returned after successful login
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
}
/// User info request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfoRequest {
    /// Stored credential identifier
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    pub instance_name: ::prost::alloc::string::String,
}
/// User info response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfoResponse {
    #[prost(bool, tag = "1")]
    pub is_login: bool,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub face: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_vip: bool,
}
/// Logout request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
    /// Which credential to unbind
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Logout response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Get binds request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBindsRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get binds response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBindsResponse {
    #[prost(message, repeated, tag = "1")]
    pub binds: ::prost::alloc::vec::Vec<BindInfo>,
}
/// Saved credential information
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
    /// Unix epoch timestamp
    #[prost(int64, tag = "3")]
    pub created_at: i64,
}
/// QR login status enum
/// Wire values mirror synctv-media-providers QRCodeStatus.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QrLoginStatus {
    Unspecified = 0,
    Expired = 1,
    NotScanned = 2,
    Scanned = 3,
    Success = 4,
}
impl QrLoginStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "QR_LOGIN_STATUS_UNSPECIFIED",
            Self::Expired => "QR_LOGIN_STATUS_EXPIRED",
            Self::NotScanned => "QR_LOGIN_STATUS_NOT_SCANNED",
            Self::Scanned => "QR_LOGIN_STATUS_SCANNED",
            Self::Success => "QR_LOGIN_STATUS_SUCCESS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "QR_LOGIN_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "QR_LOGIN_STATUS_EXPIRED" => Some(Self::Expired),
            "QR_LOGIN_STATUS_NOT_SCANNED" => Some(Self::NotScanned),
            "QR_LOGIN_STATUS_SCANNED" => Some(Self::Scanned),
            "QR_LOGIN_STATUS_SUCCESS" => Some(Self::Success),
            _ => None,
        }
    }
}
