// This file is @generated by prost-build.
/// Login request
/// SECURITY: Prefer hashed_password over password when possible to reduce plaintext exposure.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "5")]
    pub instance_name: ::prost::alloc::string::String,
    #[prost(oneof = "login_request::Credential", tags = "3, 4")]
    pub credential: ::core::option::Option<login_request::Credential>,
}
/// Nested message and enum types in `LoginRequest`.
pub mod login_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Credential {
        /// SECURITY: Plaintext credential - requires TLS in transit. Prefer hashed_password.
        #[prost(string, tag = "3")]
        Password(::prost::alloc::string::String),
        /// Hashed password preferred when available.
        #[prost(string, tag = "4")]
        HashedPassword(::prost::alloc::string::String),
    }
}
/// Login response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    /// SHA-256(host) identifier for stored credential
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
}
/// List directory request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    /// Stored credential identifier
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// Directory password (optional)
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub page: u64,
    #[prost(uint64, tag = "5")]
    pub per_page: u64,
    #[prost(bool, tag = "6")]
    pub refresh: bool,
    /// Optional provider instance name
    #[prost(string, tag = "7")]
    pub instance_name: ::prost::alloc::string::String,
}
/// List directory response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag = "1")]
    pub content: ::prost::alloc::vec::Vec<FileItem>,
    #[prost(uint64, tag = "2")]
    pub total: u64,
}
/// File/directory item
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileItem {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size: u64,
    #[prost(bool, tag = "3")]
    pub is_dir: bool,
    #[prost(uint64, tag = "4")]
    pub modified: u64,
    #[prost(string, tag = "5")]
    pub sign: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub thumb: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub r#type: u64,
}
/// Get user info request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeRequest {
    /// Stored credential identifier
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get user info response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeResponse {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub base_path: ::prost::alloc::string::String,
}
/// Logout request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
    /// Which credential to unbind
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Optional provider instance name
    #[prost(string, tag = "2")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Logout response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Get binds request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBindsRequest {
    /// Optional provider instance name
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
}
/// Get binds response
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBindsResponse {
    #[prost(message, repeated, tag = "1")]
    pub binds: ::prost::alloc::vec::Vec<BindInfo>,
}
/// Saved credential information
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    /// Unix epoch timestamp
    #[prost(int64, tag = "4")]
    pub created_at: i64,
}
